### ISSUE TITLE
🐞 [Bug]: Can't list deployments

### ISSUE THREAD

**Issue by AhmedHanafy725** [threefoldtech/tfgrid-sdk-ts#2435] opened 2024-03-14 12:29 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### which package/s did you face the problem with?

Dashboard

### What happened?

can't list the fullvm deployments

### Steps To Reproduce

1- Deploy a full vm.
2- Wait to be listed after deployment

> Note: I don't have any failed deployments

### which network/s did you face the problem on?

Dev

### version

2.3.2

### Relevant screenshots/screen records

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/41957921/1ad3087b-74f3-4254-b3a2-a1ace3768820)

### Relevant log output

```console
-
```

**Comment by A-Harby** [comment] 2024-03-17 08:34
Verified, Devnet a9928b8.

Was able to list new deployed VM.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/173c8fb1-746c-419d-a56e-0e12c8921012)
As well as the old ones.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/9df8cc40-c841-446e-ab25-a009ea3082f9)

**Comment by RoberL72** [comment] 2024-03-19 18:53
not fixed. Ever since we changed to the new dash board I can see all the contracts but none of the 8 VM's deployed

**Comment by AhmedHanafy725** [comment] 2024-03-19 19:16
@RoberL72 Can you provide more info? What are the contract IDs? Which network?

**Comment by RoberL72** [comment] 2024-03-21 10:32
Van: AhmedHanafy725 ***@***.***> 
Verzonden: dinsdag 19 maart 2024 20:17
Aan: threefoldtech/tfgrid-sdk-ts ***@***.***>
CC: RoberL72 ***@***.***>; Mention ***@***.***>
Onderwerp: Re: [threefoldtech/tfgrid-sdk-ts] 🐞 [Bug]: Can't list deployments (Issue #2435)

 

@RoberL72 <https://github.com/RoberL72>  Can you provide more info? What are the contract IDs? Which network?

**Comment by Cameron1986labeyrie** [comment] 2024-04-09 15:34
The user can't find VM deployments in the new dashboard. He deployed them in the old playground, Also, the User Deployed a new VM and got the error: relay info is not set for twin

Contract 1: 229142 
Contract 2: 257804

![img0491_g6oftz](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/152964575/e0614c65-f162-4333-a1a4-5fcec15673b5)

![f4896f2c-6d45-4739-bd0a-438ba4_1ndtxgh](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/152964575/ffcc3e8e-202d-4071-bbca-9c504b1e70ce)

![img0485_ihumt2](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/152964575/7c0c6c28-13ed-4ff6-a4f9-45f8c13c72e6)

![img0486_1lt1fa4](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/152964575/7dd1f417-3017-4d8c-b485-a6bb120d0fbe)

**Comment by Cameron1986labeyrie** [comment] 2024-04-09 15:48
VMs for the following contract IDs are not loading/available in the deployments list under full vms.

Contract : 229142
Contract : 257804

![img0486_1lt1fa4 (1)](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/152964575/a40881a1-8dc3-46f0-89f0-71426ab4d3de)
![img0485_ihumt2 (1)](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/152964575/b82dbe47-2a25-4ca6-9e13-6e32baaf0a08)
![img0491_g6oftz (1)](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/152964575/b1d96ffa-711b-417d-81a8-fa57079aa7eb)

**Comment by 0oM4R** [comment] 2024-04-16 11:30
> VMs for the following contract IDs are not loading/available in the deployments list under full vms.
> 
> Contract : 229142 Contract : 257804
> 
> ![img0486_1lt1fa4 (1)](https://private-user-images.githubusercontent.com/152964575/320914057-a40881a1-8dc3-46f0-89f0-71426ab4d3de.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMyNjcyMzIsIm5iZiI6MTcxMzI2NjkzMiwicGF0aCI6Ii8xNTI5NjQ1NzUvMzIwOTE0MDU3LWE0MDg4MWExLThkYzMtNDZmMC04OWYwLTcxNDI2YWI0ZDNkZS5qcGVnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQxNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MTZUMTEyODUyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9Mzk3OTNiMzQ0NzdlZDljNzNmNzc4MjFkNjljODE0YmFhM2VhODk1NmE3NjQ0NWExYjE4ZGIxNGMwMGRhYzdiNiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.Wc1JRGxdByMvQkxbPFTpowG24Pyuohv0d4YEDqGN9ns) ![img0485_ihumt2 (1)](https://private-user-images.githubusercontent.com/152964575/320914084-b82dbe47-2a25-4ca6-9e13-6e32baaf0a08.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMyNjcyMzIsIm5iZiI6MTcxMzI2NjkzMiwicGF0aCI6Ii8xNTI5NjQ1NzUvMzIwOTE0MDg0LWI4MmRiZTQ3LTJhMjUtNGNhNi05ZTEzLTZlMzJiYWFmMGEwOC5qcGVnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQxNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MTZUMTEyODUyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NjgzODM5ZDI3MmQzZmFlMGViNzljODVmNzI2NjkyYWJkODBkOWVkN2FiY2E3YjI0ZWEwNjQ0MTE4YjhmYzE4MiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.neuvcce5Y5YRyH7bhiw1qc7UkwLrS_1_N5apDttk1hw) ![img0491_g6oftz (1)](https://private-user-images.githubusercontent.com/152964575/320914115-b1d96ffa-711b-417d-81a8-fa57079aa7eb.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMyNjcyMzIsIm5iZiI6MTcxMzI2NjkzMiwicGF0aCI6Ii8xNTI5NjQ1NzUvMzIwOTE0MTE1LWIxZDk2ZmZhLTcxMWItNDE3ZC04MWE4LWZhNTcwNzlhYTdlYi5qcGVnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQxNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MTZUMTEyODUyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YzA1MmI3ZmQzZDIwOWU4MjExNTNiZGNjMGEwYWFhYTFkMWQ4ODMwMGEyMmZhZGFiNDlkOGU4MGE3MGI0NTg5NyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.06BbCCSixXjd-2fa28IdS5oHKlhP2nBxG-BVdw37nM8)

@Cameron1986labeyrie  could you please provide the logs ?

**Comment by Mahmoud-Emad** [comment] 2024-04-16 12:28
@Cameron1986labeyrie 

Seems to be that the issue persists, we'll actively work on resolving it. we'll investigate further and keep you updated on our progress. Please continue to monitor the issue for any updates. Thank you for your patience and understanding.

My contracts on devnet: 

- ![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/57001890/b79f0ee5-b30b-4275-b18b-7f84eaabaf4d)

My listed full VMs on devnet 

- ![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/57001890/adb1a08c-c3d2-466f-b30e-b50e4a02ccb3)

The mentioned failed Deployments

- ![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/57001890/c881bb68-019f-4fa7-8af2-d96538bb15ce)

**Comment by Mahmoud-Emad** [comment] 2024-04-17 07:00
@Cameron1986labeyrie 
Please try to provide us with better screenshots for the `Contracts List Page` and `Full VM Page`

**Comment by Mahmoud-Emad** [comment] 2024-04-17 07:39
After conducting an investigation, it has come to my attention that we previously adhered to a specific pattern for storing machine details in the old playground. As part of the transition to the new dashboard, we introduced a change to this pattern and implemented a fix to update all instances of the old pattern to the new one. However, it appears that the fix is not functioning as expected.

### Old Pattern:
![Old Pattern](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/57001890/0fa79e6b-01f8-43f7-83f3-1705ce576d8f)

### New Pattern:
![New Pattern](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/57001890/f35330ff-c428-47b2-b595-f24976c7339b)

**Comment by 0oM4R** [comment] 2024-04-17 16:37
Investigation: 
the type in deployment data  is Fullvm, this can't be listed in fullvm deployment list, and should be migrated and listed in vm deployment list, trying to confirm that the migration happened and deployments appears on vm deployments table

**Comment by 0oM4R** [comment] 2024-04-18 09:21
I couldn't reproduce deployment with the mentioned deployment data. For now, you should find the missing deployments on vm deployment table.

**Comment by MohamedElmdary** [comment] 2024-04-18 12:58
Tried to reproduce this issue and was able to do so by manually change type and projectname in metadata in grid_client
however after deploying I was not able to find that machine in any path

**Comment by Mahmoud-Emad** [comment] 2024-04-21 08:21
@Cameron1986labeyrie 
What did you use to deploy both machines?

**Comment by tzumby** [comment] 2024-05-06 12:37
I'm running into a similar problem, trying to list the deployments with this command used to work, but now it returns an empty array:

```
  const result = await gridClient.machines.getObj(vms);
```

This is the payload used to create the VM:

```
  const vms = {
    name: '608e9aa00666',
    network: {
      name: '9cec1820a56f',
      ip_range: '10.238.0.0/16',
      addAccess: undefined,
      accessNodeId: undefined,
      myceliumSeeds: undefined
    },
    machines: [
      {
        name: '52839ffc800d',
        node_id: 312,
        disks: [],
        qsfs_disks: undefined,
        public_ip: true,
        public_ip6: undefined,
        planetary: true,
        mycelium: false,
        myceliumSeed: undefined,
        cpu: 2,
        memory: 2048,
        rootfs_size: 0,
        flist: 'xxx',
        entrypoint: '/sbin/zinit init',
        env: [],
        ip: undefined,
        corex: undefined,
        solutionProviderId: 2,
        zlogsOutput: undefined,
        gpus: undefined
      }
    ],
    metadata: '',
    description: 'xxx node'
  };

```

**Comment by Mahmoud-Emad** [comment] 2024-05-07 07:58
Hello @tzumby :)

I just deployed a machine from the `grid-client` and I was able to list it from the dashboard

this is the machine data I have used 

```ts
  const vms: MachinesModel = {
    name,
    network: {
      name: "wedtest",
      ip_range: "10.249.0.0/16",
    },
    machines: [
      {
        name: "tobetested",
        node_id: 11,
        disks: [
          {
            name: "wedDisk",
            size: 8,
            mountpoint: "/testdisk",
          },
        ],
        public_ip: false,
        public_ip6: false,
        planetary: true,
        mycelium: false,
        cpu: 1,
        memory: 1024 * 2,
        rootfs_size: 0,
        flist: "https://hub.grid.tf/tf-official-apps/base:latest.flist",
        entrypoint: "/sbin/zinit init",
        env: {
          SSH_KEY: config.ssh_key,
        },
      },
    ],
    metadata: "",
    description: "test deploying VMs via ts grid3 client",
  };
```

I named the machine `tobetested`, and I would like to share that the deployment was successful!:

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/57001890/f3bd0c6c-df17-4e19-a017-24e9836ad47a)

Here's a screenshot from the dashboard showing the deployed machine:
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/57001890/b6f62217-8bf5-4d9d-9330-46c7cc866ac0)

Please make sure that you are connecting to the dashboard by the same account wallet secret you used when you deployed the machine from the `grid-client`

As you can see, the machine `tobetested` is listed on the dashboard. To ensure a smooth experience:

1. Connect to the dashboard using the same account wallet secret used during machine deployment.
2. Enable the Show All Deployments switch to view all deployments.
3. Make sure you are connected to the same network on both the dashboard and the Grid client.

**Comment by tzumby** [comment] 2024-05-07 14:34
Hey @MohamedElmdary , I can already see them in the Dashboard, please read my comment, they don't show up when I try to call `getObj`

**Comment by Mahmoud-Emad** [comment] 2024-05-08 08:07
> Hey @MohamedElmdary , I can already see them in the Dashboard, please read my comment, they don't show up when I try to call `getObj`

If that is the case, I think you need to send the name of the deployment not the `vms` interface 

```ts
  const name = "newVMS";
  const grid3 = await getClient(`vm/${name}`);

  const vms: MachinesModel = {
    name,
    network: {
      name: "wedtest",
      ip_range: "10.249.0.0/16",
    },
    machines: [
      {
        name: "testvm",
        node_id: 11,
        disks: [
          {
            name: "wedDisk",
            size: 8,
            mountpoint: "/testdisk",
          },
        ],
        public_ip: false,
        public_ip6: false,
        planetary: true,
        mycelium: false,
        cpu: 1,
        memory: 1024 * 2,
        rootfs_size: 0,
        flist: "https://hub.grid.tf/tf-official-apps/base:latest.flist",
        entrypoint: "/sbin/zinit init",
        env: {
          SSH_KEY: config.ssh_key,
        },
      },
    ],
    metadata: "",
    description: "test deploying VMs via ts grid3 client",
  };

const deployed = await client.machines.deploy(vms);
const deploymentDetails = await client.machines.getObj(name);
```

**Comment by tzumby** [comment] 2024-05-08 10:46
Let me check this, I'm pretty sure i had both name and vms as parameters there with the same result.

**Comment by tzumby** [comment] 2024-05-08 10:49
Yes, confirmed that `const deploymentDetails = await client.machines.getObj(name);` does not work either

**Comment by Mahmoud-Emad** [comment] 2024-05-08 11:14
@tzumby Any errors? logs?

**Comment by Mahmoud-Emad** [comment] 2024-05-08 13:53
@tzumby 

I just used your payload and was able to deploy/list the deployment 

```json
[
  {
    version: 0,
    contractId: 109538,
    nodeId: 11,
    name: '52839ffc800d',
    created: 1715170810,
    status: 'ok',
    message: '',
    flist: 'https://hub.grid.tf/tf-official-apps/base:latest.flist',
    publicIP: null,
    planetary: '302:9e63:7d43:b742:b2a4:5133:63ba:6b5',
    myceliumIP: '',
    interfaces: [ { network: '9cec1820a56f', ip: '10.238.2.2' } ],
    capacity: { cpu: 2, memory: 2048 },
    mounts: [],
    env: {},
    entrypoint: '/sbin/zinit init',
    metadata: '',
    description: 'xxx node',
    rootfs_size: 0,
    corex: false,
    gpu: []
  }
]
'================= Getting deployment information ================='
disconnecting
```
However, I faced some errors and I'm not sure if you faced some of them or not 

1. The filst should be a valid URL for a real flist not `xxx`
2. The other errors were about the availability of reserving a public IP and the deployment name that was taken by you, as you see I just added one more char to fix it
3. The `env` should be an object `{}` not an array `[]`

**Comment by tzumby** [comment] 2024-05-08 15:02
Yes, I redacted those fields out for the flist and the name. There's no errors. The deploys are going successfully, it's just that the deployments returns an empty array. In the logs I can see the contract ids and everything, it seems like there's something wrong with getting them after deploying

**Comment by tzumby** [comment] 2024-05-08 15:02
Did you try this and successfully returned the deployments ? 

```
const deploymentDetails = await client.machines.getObj(name);
```

**Comment by Mahmoud-Emad** [comment] 2024-05-14 14:16
## Issue update

### Work done

a new migration function added to the `Dashboard` to migrate the old `Fullvm` deployment types to `vm`

**Comment by Mahmoud-Emad** [comment] 2024-05-15 10:18
## Issue update 

### Work done 

- Updated the import of 'BaseModule' in 'migration.ts' to be local dir instead of the dist one to fix the un-exported issue
- Flat the array of the contracts then loop over them all
- Updated the moduleName after listing the 'Fullvm' to 'vm' again to list the other deployments
- Pushed the newly changed contract to the 'newContracts' array to avoid the lag of gql
- Updated the 'moduleName' in 'base.ts' to take 'Fullvm' if the 'moduleNames' is undefined

**Comment by Mahmoud-Emad** [comment] 2024-05-19 15:11
## issue update 

### Work done
- Replaced the 'exact' search with 'contains' algo by adding 'includes' when searching on the 'projectName'.
- Introduced a new field 'updatedAt' in the 'GqlNodeContract' type to store the updated time in it.
- Added a condition on checking on the 'updatedAt' field to replace the newly added contract with the Gql contract.

**Comment by khaledyoussef24** [comment] 2024-05-21 10:03
can you mention where to find the latest fields of updatedAt and search to verify ?

**Comment by Mahmoud-Emad** [comment] 2024-05-21 10:29
> can you mention where to find the latest fields of updatedAt and search to verify ?

it's defined in the `GqlNodeContract` interface, you can deploy a machine using the `gridClient/single_vm.ts` script to see it.

**Comment by khaledyoussef24** [comment] 2024-06-11 10:40
verified on staging 
version : 408184e
changed the name of the single vm  (type,project) in the machine files from `vm` to `Fullvm`
and deployed it using the grid client.



![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/066f62a9-ffed-4876-9b7f-441b2fdd35d6)

![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/fc78c7f4-fea2-4468-be23-06d46271e6a2)


on the staging worked fine after @Mahmoud-Emad  changes:
![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/b3ebaec5-964a-4f30-9a04-35d658b0abd4)
while in the dashboard it did not load(normal devnet):
![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/f8765aaa-a8e7-4109-930c-eb54364ffead)

**Closed** 2024-06-11 10:54 UTC
Labels: type_bug, dashboard
