### ISSUE TITLE
Billing rate not seen in Playground (New) - Tommy

### ISSUE THREAD

**Issue by amandacaster** [threefoldtech/tfgrid-sdk-ts#1439] opened 2023-11-20 10:52 UTC
### Description

The user came in saying he was not able to see the billing rate on https://playground.grid.tf/#/ but was able to see in https://play.grid.tf/#/

### Steps to reproduce

1. Go to https://playground.grid.tf
2. Downloaded a Full VM and waited for a couple of hours 
3.  Found that the billing rates were still not seen, however on https://play.grid.tf/#/ I can see the billing rate.  (Have attached images)
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/88147124/1025615d-e8df-4d0c-bccb-b859c4d3dee8) 
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/88147124/2d5a48b0-35e5-4b4c-b17c-368d8a28594d)

**Comment by mohamedamer453** [comment] 2023-11-23 12:05
Update:

Investigation:

Checked my previous deployments on the new playground and the billing rate appeared without any issues.

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/101194226/165e1b14-f7e8-4e5a-989f-f20a3db044fb)

and created a couple of new ones to confirm that the issue is not happening, will update the issue with these deployments with the next billing cycle.

**Comment by mohamedamer453** [comment] 2023-11-23 13:21
Update:

Investigation:

After checking the state of the deployments the billing rate appeared normally without any issues after the billing cycle.

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/101194226/5244a0a1-5bf6-4fdb-aeb8-061b78ac7152)

and also another micro vm that was deployed around the same time got its billing rate without any issues.

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/101194226/a503a646-b304-4363-823a-14effcc200c0)


The issue seems to be resolved with the new playground and therefore it'll be resolved with the 3.13 release.

**Comment by amandacaster** [comment] 2023-11-23 13:49
Thanks @mohamedamer453, I will let the user know.

**Comment by A-Harby** [comment] 2023-12-11 11:35
I also tried few deployment on new dashboard and mainnet dashboard and billing rate was fine.

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/09b3c6b9-1782-43bb-aef6-edaef43cd33c)

**Comment by ramezsaeed** [comment] 2023-12-19 11:00
verified:
- Devnet
- 13a87cf

**Closed by ramezsaeed** 2023-12-19 11:00 UTC
Labels: type_bug
