### ISSUE TITLE
password field is shared between login and connect tabs

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/tfgrid-sdk-ts#518] opened 2023-06-12 06:24 UTC
steps to reproduce

- open playground
- type a password
- go to connect page
- you will find the password prefilled

**Comment by Mahmoud-Emad** [comment] 2023-06-12 07:33
This issue is a duplicate of #510

**Comment by A-Harby** [comment] 2023-06-12 10:18
Verified,
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/68626d3e-6445-42ba-9c49-17e51ac9a9ad)

**Closed by A-Harby** 2023-06-12 10:18 UTC
Labels: type_feature, playground
