### ISSUE TITLE
(Mainnet Verification) Storage pool error : "not enough space left in pools" 

### ISSUE THREAD

**Issue by 0oM4R** [threefoldtech/tfgrid-sdk-ts#886] opened 2023-07-31 07:31 UTC
#### using grid client v2.0.0 on main net

I tried to deploy vm with 2 disks  200GB and 700GB;  
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/62248851/7dceda94-5a82-4000-93e7-432f4680d64f)

this order failed but if i reverse the disks order  to be  [700,200]  the deployment success 
 

####  grid client logs 
```
➜  grid_client git:(v2.0.0) ✗ yarn run ts-node --project tsconfig-node.json scripts/single_vm.ts         
yarn run v1.22.19
$ /home/kassem/threefold/tfgrid-sdk-ts/node_modules/.bin/ts-node --project tsconfig-node.json scripts/single_vm.ts
Credentials not all found in env variables. Loading all credentials from default config.json...
2023-07-30 19:40:07        API/INIT: RPC methods not decorated: transaction_unstable_submitAndWatch, transaction_unstable_unwatch
2023-07-30 19:40:07        API/INIT: Not decorating runtime apis without matching versions: TransactionPaymentApi/2 (1 known)
Validation succeed
Start creating the machine deployment with name newVMS
Loading network wedtest
Creating a vm on node: 8, network: wedtest with private ip: 10.249.2.2
Merging workloads
Validation succeed
Deploying on node_id: 8
Lock acquired
2023-07-30 19:40:24        API/INIT: Not decorating runtime apis without matching versions: TransactionPaymentApi/2 (1 known)
phase: {"applyExtrinsic":10}, section: balances, method: Withdraw, data: ["5HHRg2nVfTXD9StGihrjHre5LhC2xVRZhBYvVqoorvsqo5F5",10198]
phase: {"applyExtrinsic":10}, section: smartContractModule, method: ContractCreated, data: [{"version":4,"state":{"created":null},"contractId":46199,"twinId":8574,"contractType":{"nodeContract":{"nodeId":8,"deploymentHash":"0x6137613830333834386531373830333930333139343031666263353762326133","deploymentData":"0x7b2274797065223a22766d222c226e616d65223a226e6577564d53222c2270726f6a6563744e616d65223a22227d","publicIps":0,"publicIpsList":[]}},"solutionProviderId":null}]
phase: {"applyExtrinsic":10}, section: utility, method: ItemCompleted, data: []
phase: {"applyExtrinsic":10}, section: utility, method: BatchCompleted, data: []
phase: {"applyExtrinsic":10}, section: balances, method: Deposit, data: ["5Gn5ceQKEeNN1XdhhhcnN1hhQLiHmX1Ymi5kgvH2bJpJtyd4",10198]
phase: {"applyExtrinsic":10}, section: transactionPayment, method: TransactionFeePaid, data: ["5HHRg2nVfTXD9StGihrjHre5LhC2xVRZhBYvVqoorvsqo5F5",10198,0]
phase: {"applyExtrinsic":10}, section: system, method: ExtrinsicSuccess, data: [{"weight":{"refTime":2053535172,"proofSize":0},"class":"Normal","paysFee":"Yes"}]
Lock released
Sending deployment to node_id: 8
A deployment has been created on node_id: 8 with contract_id: 46199
Waiting for deployment with contract_id: 46199 to be ready
Rolling back deployments
Deleting contract id 46199
Lock acquired
2023-07-30 19:40:30        API/INIT: Not decorating runtime apis without matching versions: TransactionPaymentApi/2 (1 known)
phase: {"applyExtrinsic":1}, section: balances, method: Withdraw, data: ["5HHRg2nVfTXD9StGihrjHre5LhC2xVRZhBYvVqoorvsqo5F5",10118]
phase: {"applyExtrinsic":1}, section: smartContractModule, method: ContractBilled, data: [{"contractId":46199,"timestamp":1690735230,"discountLevel":"None","amountBilled":0}]
phase: {"applyExtrinsic":1}, section: smartContractModule, method: NodeContractCanceled, data: [46199,8,8574]
phase: {"applyExtrinsic":1}, section: utility, method: ItemCompleted, data: []
phase: {"applyExtrinsic":1}, section: utility, method: BatchCompleted, data: []
phase: {"applyExtrinsic":1}, section: balances, method: Deposit, data: ["5F6jW3dsjEx1TfJLmrtS2V9ftyCvPe5TjbHMoKisCWMyR2Qh",10118]
phase: {"applyExtrinsic":1}, section: transactionPayment, method: TransactionFeePaid, data: ["5HHRg2nVfTXD9StGihrjHre5LhC2xVRZhBYvVqoorvsqo5F5",10118,0]
phase: {"applyExtrinsic":1}, section: system, method: ExtrinsicSuccess, data: [{"weight":{"refTime":227149172,"proofSize":0},"class":"Normal","paysFee":"Yes"}]
Lock released
/home/kassem/threefold/tfgrid-sdk-ts/packages/grid_client/src/high_level/twinDeploymentHandler.ts:524
      throw Error(e);
            ^
Error: Error: Failed to deploy zmount with name wedDisk2 on node 8 due to: failed to find a candidate to host vdisk of size '751619276800': not enough space left in pools of this type ssd
    at TwinDeploymentHandler.handle (/home/kassem/threefold/tfgrid-sdk-ts/packages/grid_client/src/high_level/twinDeploymentHandler.ts:524:13)
at async MachinesModule.deploy (/home/kassem/threefold/tfgrid-sdk-ts/packages/grid_client/src/modules/machines.ts:92:23)
    at async MachinesModule.descriptor.value (/home/kassem/threefold/tfgrid-sdk-ts/packages/grid_client/src/modules/utils.ts:14:12)
    at async MachinesModule.descriptor.value (/home/kassem/threefold/tfgrid-sdk-ts/packages/grid_client/src/helpers/validator.ts:23:12)
    at async main (/home/kassem/threefold/tfgrid-sdk-ts/packages/grid_client/scripts/single_vm.ts:50:15)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

#### storage pool of node 8 

```
[
  {
    name: '27e83eaa-89ae-48fd-96b5-2ee921675280',
    type: 'ssd',
    size: 1000204886016,
    used: 102540247040
  },
  {
    name: 'a20ee9b4-32b2-4afc-8e29-cb50c4ab98da',
    type: 'ssd',
    size: 1000204886016,
    used: 751619276800
  },
  {
    name: 'cf49b806-a456-48d9-b04a-7d17d2c80b0d',
    type: 'hdd',
    size: 12000138625024,
    used: 85899345920
  },
  {
    name: 'dd8fbdfb-c1b9-44a8-9009-0cbefad9b658',
    type: 'hdd',
    size: 12000138625024,
    used: 0
  },
  {
    name: '68a1b08a-9206-48bc-9eae-7d4ecd8db770',
    type: 'hdd',
    size: 12000138625024,
    used: 0
  },
  {
    name: 'efe08448-396c-4a84-8256-5fae4cf61883',
    type: 'hdd',
    size: 12000138625024,
    used: 0
  },
  {
    name: '13738b20-a05e-4d08-8dc2-30a61f2b28fe',
    type: 'hdd',
    size: 12000138625024,
    used: 0
  },
  {
    name: '1278e7ce-1963-47df-960b-6a0efc50c051',
    type: 'hdd',
    size: 12000138625024,
    used: 0
  },
  {
    name: '609b1a8c-7db4-4e88-9d40-28ea87ae538a',
    type: 'hdd',
    size: 12000138625024,
    used: 0
  },
  {
    name: 'cd00bd7b-7272-4dea-aa54-8a1cbf1e0c8c',
    type: 'hdd',
    size: 12000138625024,
    used: 0
  },
  {
    name: '6a4f5ff2-fee6-49fa-a6bd-9b0b2a2d3226',
    type: 'hdd',
    size: 12000138625024,
    used: 0
  },
  {
    name: '33997ec1-b531-47c0-a74d-bc4f82e57151',
    type: 'hdd',
    size: 12000138625024,
    used: 0
  },
  {
    name: '2491d567-3d87-4ce1-9f74-e78c6da51a96',
    type: 'hdd',
    size: 12000138625024,
    used: 0
  },
  {
    name: '97fd61c4-be8a-42eb-8b16-338036c5afbc',
    type: 'hdd',
    size: 12000138625024,
    used: 0
  }
]
```

#### the  succeeded  deployment
```
{
  contracts: {
    created: [
      {
        version: 4,
        state: { created: null },
        contractId: 46200,
        twinId: 8574,
        contractType: {
          nodeContract: {
            nodeId: 8,
            deploymentHash: '98b5abc6e4b817852ff85d1c9ece6f8a',
            deploymentData: '{"type":"vm","name":"newVMS","projectName":""}',
            publicIps: 0,
            publicIpsList: []
          }
        },
        solutionProviderId: null
      }
    ],
    updated: [],
    deleted: []
  },
  wireguard_config: ''
}
[
  {
    version: 0,
    contractId: 46200,
    nodeId: 8,
    name: 'testvm',
    created: 1690735530,
    status: 'ok',
    message: '',
    flist: 'https://hub.grid.tf/tf-official-apps/base:latest.flist',
    publicIP: null,
    planetary: '302:1297:52fe:57ba:6565:531b:87e5:c830',
    interfaces: [ { network: 'wedtest', ip: '10.249.2.2' } ],
    capacity: { cpu: 1, memory: 1024 },
    mounts: [
      {
        name: 'wedDisk',
        mountPoint: '/testdisk',
        size: 751619276800,
        state: 'ok',
        message: ''
      },
      {
        name: 'wedDisk2',
        mountPoint: '/testdk',
        size: 214748364800,
        state: 'ok',
        message: ''
      }
    ],
    env: {
      SSH_KEY: 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDNFMdYHGcGqWsE7H1eqsWaXwOQQQrh6bYWsKKGa7KswNa8BhyEK9bjxEs13LvIVPUckn/wVVqlH0qFAc8JjBRmSjGdDjyZIvawOIyDX/Jr0fPAyS3e8eL+FvuJVW1OCKZ4DmGYgNiEYFDZ0uxf6lyfJyYsiTxzeukHOjtDe3xIg660aYdWKV4bbog9AmkdXL7x0lTkUb+ERVhMCvtIFE7YKGZqeEovL6tgXl9U/ApdXK/xT0283CWoKBQVcvZUEqimtWTaEFekFD4PTDkwfUg6WZY6Gy6yTU4HESziSh5e0raH7mP4YJ8tZsdtnfIL+NRvReUqFz8goG6Dm0nvsvwcI8jJhH8lGbPxd6hqbvk+PnttZRr5uxiIJwIx/98fW+mAL0N7AScRklFSjQgr4dRTqZ+/TXyUj9E0x/nyaEpRuj83SzLSwFsc2izoxNCSJDz3m5t7RW2Inm3X3oZmkFOdWL4Y1yGIHcFY0i9LSgHYaQpfLpDz4WnlkkU8cyf73Ic= rawda@rawda-Inspiron-3576'
    },
    entrypoint: '/sbin/zinit init',
    metadata: '{"type":"vm","name":"newVMS","projectName":""}',
    description: 'test deploying VMs via ts grid3 client',
    rootfs_size: 0,
    corex: false
  }
]
```

**Comment by muhamadazmy** [comment] 2023-07-31 09:05
The problem is ZOS tries to `balance` the load on the disks by making sure disks that already been used by other workloads to have balanced load, instead of filling a full disk entirely before moving to the next. 

In other words, if ZOS managed to fit all allocated disk on a single physical disks, we might hit IO limit on that one disk while others are free. Inestead ZOS make sure that if we already have multiple physical disks being used, that new workloads is distributed evenly on all disks as much as possible to make sure all disks are serving IOs

In the issue above, the node basically put the first disks (200G) on the one with most free space. Then on allocating that second disks there were NO enough free space.

This can be solved in either two cases:
- we can change the allocation policy on ZOS to actually fill a complete disk before allocating on the other disks. Risking having one disk serving the most IO requests but efficiently allocating workloads
- make sure that the clients always puts disks with most spaces up in a deployment so they get allocated first. but this can't be granted that all clients follow this scheme.

**Comment by AhmedHanafy725** [comment] 2023-07-31 09:39
> * make sure that the clients always puts disks with most spaces up in a deployment so they get allocated first. but this can't be granted that all clients follow this scheme.

can't we sort the requested disks by the user on ZOS before starting to look for their candidates? That's after calculating the challenge of the deployment so we don't break the challenge and if the client is not sorting this disk, it won't be an issue

**Comment by muhamadazmy** [comment] 2023-07-31 09:52
Yes, i think this is the best solution, we already do some ordering before running the deployment. (for example network has to be done first, before the VMs, etc..) so we can add  sub ordering in case of disk type to do bigger disks first.

**Comment by 0oM4R** [comment] 2023-08-08 08:56
This should be fix in grid client, now we are checking the storage pool before deployment.

**Comment by 0oM4R** [comment] 2023-08-08 08:57
also playground check if the selected node have suitable storage pool #912

**Comment by mohamedamer453** [comment] 2023-08-16 11:18
awaiting mainnet deployment since all the nodes on dev, qa, test nets only have 1 ssd and to verify this issue a node must have more than 1 ssd

**Comment by khaledyoussef24** [comment] 2023-09-12 13:26
verified on mainnet 
deployed a vm with 2 different storage and working fine and deployed with the required space
![Screenshot from 2023-09-12 16-25-04](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/2379bc61-2dda-47da-9b76-cbcec4c82875)
![Screenshot from 2023-09-12 16-24-50](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/fbf786ed-8a6b-42a9-a890-d92be992b802)

**Closed by khaledyoussef24** 2023-09-12 13:26 UTC
Labels: grid_client, playground
