### ISSUE TITLE
The state cards need to be handled

### ISSUE THREAD

**Issue by Mahmoud-Emad** [threefoldtech/tfgrid-sdk-ts#1994] opened 2024-01-16 07:49 UTC
- ![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/57001890/20028752-1442-41eb-8b27-49b1b3343cb3)

**Comment by AlaaElattar** [comment] 2024-01-17 11:47
- duplicate of https://github.com/threefoldtech/tfgrid-sdk-ts/issues/1983

**Closed by AlaaElattar** 2024-01-17 11:47 UTC
Labels: type_bug, dashboard, enhancements
