### ISSUE TITLE
public ips node filter is not working

### ISSUE THREAD

**Issue by khaledyoussef24** [threefoldtech/tfgrid-sdk-ts#2050] opened 2024-01-21 07:21 UTC
### Description

public ips node in load nodes is not working
env used : devnet
version : https://github.com/threefoldtech/tfgrid-sdk-ts/commit/5b50681261cf6e97e63a9dc4eac5535210aaae9b
<img width="1440" alt="Screenshot 2024-01-21 at 9 12 04 AM" src="https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/21561b8c-6148-4b84-847c-e1994e290f8b">

<img width="1179" alt="Screenshot 2024-01-21 at 9 20 17 AM" src="https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/cd258033-1fff-44c8-bc13-e8447e8793bb">
<img width="1440" alt="Screenshot 2024-01-21 at 9 19 39 AM" src="https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/0b4aad3d-af0a-4e4e-ad14-c722414cbe24">

**Comment by AlaaElattar** [comment] 2024-01-22 14:31
### Work In Progress (WIP):
- after investigation. i found that checking farm ips is done after merging workloads.
- still looking for a way to handle it earlier.

**Comment by khaledyoussef24** [comment] 2024-01-24 05:15
can not produce the issue anymore .
tried the same scenarios as last time but did not work.
will re-open if i could produce it again.

**Comment by khaledyoussef24** [comment] 2024-01-24 11:12
the issue still exist![telegram-cloud-photo-size-4-5875128825996754705-y](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/deef862c-4728-4a01-a2bb-5927ea2bca36)

**Comment by sameh-farouk** [comment] 2024-01-24 12:31
related to https://github.com/threefoldtech/tfchain_graphql/issues/151

the processor update public_ip table when it create or update a contract. so this related to the the contracts issue and should be fixed when the ops deploy the new version ([request](https://github.com/threefoldtech/tf_operations/issues/2243))

**Comment by AlaaElattar** [comment] 2024-01-28 09:12
- As Graghql released to `v2.11.6`, the problem shouldn't exist anymore.

**Comment by khaledyoussef24** [comment] 2024-01-28 12:51
made a four or more deployments with public ip and did not face the same issue again

the issue is no more longer reproducable

**Comment by Mahmoud-Emad** [comment] 2024-01-30 16:40
I remember we threw this error to inform the user if the selected farm has enough IPs. The question is, why doesn't it pass the IP field when filtering to get nodes?

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/57001890/a8d306e6-af5f-431c-b395-df6bcfa56c94)

as you see here these are the nodes I got
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/57001890/28e3e46a-bcd0-4806-8445-35c61e61385d)

**Comment by AlaaElattar** [comment] 2024-01-31 10:40
### Work In Progress (WIP):
- I deployed vm with public ip and the filtration worked fine.

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/54944491/bc1dd84f-151e-42e3-af48-cd0fe8be4fed)

- Then, I tried to deploy caprover but i got no nodes were found as i took last public ip.

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/54944491/89e6a67d-b307-4e2f-ad79-199b15ac97f3)

- I deleted the vm to free the public ip, then went to deploy caprover.

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/54944491/b5484933-1238-4a4b-be93-230f57e2e2dc)
 
- when i tried to deploy worker to the caprover i got no nodes were found.

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/54944491/1622fe77-7c36-4bf2-85b6-c5b965555f8e)

**Comment by AlaaElattar** [comment] 2024-01-31 10:41
> ### Work In Progress (WIP):
> * I deployed vm with public ip and the filtration worked fine.
> 
> ![image](https://private-user-images.githubusercontent.com/54944491/301128749-bc1dd84f-151e-42e3-af48-cd0fe8be4fed.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY2OTc5MDQsIm5iZiI6MTcwNjY5NzYwNCwicGF0aCI6Ii81NDk0NDQ5MS8zMDExMjg3NDktYmMxZGQ4NGYtMTUxZS00MmUzLWFmNDgtY2QwZmU4YmU0ZmVkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTMxVDEwNDAwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJiNWY2YWNiZjVhOTEzMjY3YzEwOWUyYjI2ZjNkZTAzNmZmODQ0MTgwNDI3ZGYwYTc5MDUxMGFiNTBlYWM5YzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.yrxgxwR-Xbeq14e8lkf2Hqo3tzimJcpypaae-qDhTNw)
> 
> * Then, I tried to deploy caprover but i got no nodes were found as i took last public ip.
> 
> ![image](https://private-user-images.githubusercontent.com/54944491/301129060-89e6a67d-b307-4e2f-ad79-199b15ac97f3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY2OTc5MDUsIm5iZiI6MTcwNjY5NzYwNSwicGF0aCI6Ii81NDk0NDQ5MS8zMDExMjkwNjAtODllNmE2N2QtYjMwNy00ZTJmLWFkNzktMTk5YjE1YWM5N2YzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTMxVDEwNDAwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIzNzA0ZTYxYmM2ZDRlN2M2MzgxZDI4MjRjOGY1MmFlYjJiMmQ2YmQ4M2Y0OTEwODU4MzhlYmU0OGQwYmY4YmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ry4vNHltXOSxThievFKSmzKAawukkVyB5HnTuMvV_Ao)
> 
> * I deleted the vm to free the public ip, then went to deploy caprover.
> 
> ![image](https://private-user-images.githubusercontent.com/54944491/301129895-b5484933-1238-4a4b-be93-230f57e2e2dc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY2OTc5MDUsIm5iZiI6MTcwNjY5NzYwNSwicGF0aCI6Ii81NDk0NDQ5MS8zMDExMjk4OTUtYjU0ODQ5MzMtMTIzOC00YTRiLWJlOTMtMjMwZjU3ZTJlMmRjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTMxVDEwNDAwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUzMWJkZmI0NmYwN2RhYjE3YzVkMzU4ZGRiODNkNjY5NTRkMjA0ZTM2MzZhY2MzYWIwM2UxMDkwMGVkYjQxNDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.45sznZh-22zdaf7sGRC65fJMsO8b94D_kpM0rjg6I8M)
> 
> * when i tried to deploy worker to the caprover i got no nodes were found.
> 
> ![image](https://private-user-images.githubusercontent.com/54944491/301130111-1622fe77-7c36-4bf2-85b6-c5b965555f8e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY2OTc5MDUsIm5iZiI6MTcwNjY5NzYwNSwicGF0aCI6Ii81NDk0NDQ5MS8zMDExMzAxMTEtMTYyMmZlNzctN2MzNi00YmYyLTg1YjYtYzViOTY1NTU1ZjhlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTMxVDEwNDAwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA1ZGE0NGFiOGUxMDcwYmE4NjFiNTBhYWU4ZGEwNWY3Y2ZhOTc5MmUwN2IzNjA0ZTMyY2U1ODlmYjZiNDM0YWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.hBlBgAGBn2mTt_tjIdEr4jtjHC0j9rXRiMpFTpvpRFw)

- i was also checking the public ips on freefarm from graphql at the same time, and there was no difference at any step.

**Comment by AlaaElattar** [comment] 2024-01-31 10:45
- also manually the filtration works fine

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/54944491/a7d1cfd7-af65-445c-9010-98fea83a23ce)

**Comment by AlaaElattar** [comment] 2024-01-31 10:49
> I remember we threw this error to inform the user if the selected farm has enough IPs. The question is, why doesn't it pass the IP field when filtering to get nodes?
> 
> ![image](https://private-user-images.githubusercontent.com/57001890/300891070-a8d306e6-af5f-431c-b395-df6bcfa56c94.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY2OTcxNDAsIm5iZiI6MTcwNjY5Njg0MCwicGF0aCI6Ii81NzAwMTg5MC8zMDA4OTEwNzAtYThkMzA2ZTYtYWY1Zi00MzFjLWIzOTUtZGY2YmNmYTU2Yzk0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTMxVDEwMjcyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJkODY4MGM3NzI2N2U0YTQxOTkzZmE0MjI1NjQxMjZjOGQ3YjYyODc1ZjY0Y2RjNDFjNTU1N2M2MjZhZjAzZGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.-YwYrwjJFq5iMqfMHZhAFVTmL-XfJ90p7xPebPRZq18)
> 
> as you see here these are the nodes I got ![image](https://private-user-images.githubusercontent.com/57001890/300891156-28e3e46a-bcd0-4806-8445-35c61e61385d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY2OTcxNDAsIm5iZiI6MTcwNjY5Njg0MCwicGF0aCI6Ii81NzAwMTg5MC8zMDA4OTExNTYtMjhlM2U0NmEtYmNkMC00ODA2LTg0NDUtMzVjNjFlNjEzODVkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTMxVDEwMjcyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVkZDhmNzRlNTc5OWM5MjY1ODk4ZDI0OTU3YTY2NTMyMTgwNjlkOGI2YzVmOTliY2E4MjBkMmIwMDQ4NzEzZDImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.GMOJVBoAsbEXzAJM75ABlodQtYaZwGpvbhrEUWAvc2s)

- unable to reproduce this

**Comment by AhmedHanafy725** [comment] 2024-01-31 10:58
I think what happened is a race condition. Someone was deploying at the same time and he got the last public ip in the farm before you. And nothing can be done in this case.

**Comment by khaledyoussef24** [comment] 2024-01-31 16:21
is there any solution that we can do so we can avoid this concurrency?

**Comment by AhmedHanafy725** [comment] 2024-02-01 10:16
This can rarely happen and TFchain already rejecting the deployment in case the ip got taken. We will support this #1822 to make the client reject the deployment too. But nothing we can do in the playground.

**Closed** 2024-02-04 13:38 UTC
Labels: type_bug, dashboard
