### ISSUE TITLE
TFChain module tests and account creation are failing on qanet

### ISSUE THREAD

**Issue by mohamedamer453** [threefoldtech/tfgrid-sdk-ts#905] opened 2023-08-03 09:01 UTC
### Description

tfchain module [tests](https://github.com/threefoldtech/tfgrid-sdk-ts/blob/development/packages/grid_client/tests/modules/tfchain.test.ts) are failing on qanet with the following error.

```
Request failed with status code 500
```

Same issue also happens from the playground while creating a new account.

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/101194226/3c79b438-54cd-4a12-8153-d239d9ad6f8b)

```
index-63cfd666.js:160     POST https://activation.qa.grid.tf/activation/activate 500
```

### Logs

Full logs from running the tests https://gist.github.com/mohamedamer453/0de17f39fb503a803fc906aabf331ccf

### Environment

- Network: `qanet`
- Playground Version: `2.1.0-rc5`
- Grid client Version: `v2.1.0-rc5`

**Comment by Mahmoud-Emad** [comment] 2023-08-10 09:10
After verification, this is not a valid issue anymore so can you please verify and close it?

**Comment by khaledyoussef24** [comment] 2023-08-10 10:00
the issue is no longer reproducible 
verified on devnet and qanet 
![Screenshot from 2023-08-10 12-59-22](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/b5413b1f-5345-49f8-9f54-2bf7654acaa7)
[Screencast from 08-10-2023 12:58:32 PM.webm](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/aaf05925-bf4a-4c5a-847f-b7ee1cdcd085)

**Closed by khaledyoussef24** 2023-08-10 10:00 UTC
Labels: type_bug, grid_client, playground
