### ISSUE TITLE
Ensure that the `@ValidateMembers()` decorator is included in all workload tests, such as the `ZMachine` workload.

### ISSUE THREAD

**Issue by Mahmoud-Emad** [threefoldtech/tfgrid-sdk-ts#3073] opened 2024-07-03 08:50 UTC
### Which package/s are you suggesting this feature for?

Dashboard

### Is your feature request related to a problem? Please describe

A new validation role has been added to the `GridClient` for the `Compute Capacity` module. It needs to be added to the other modules as well.

### Describe the solution you'd like

A new validation role has been added to the `GridClient` for the `Compute Capacity` module. It needs to be added to the other modules as well.

**Comment by AhmedHanafy725** [comment] 2024-07-08 11:55
duplicate of #3038

**Closed by AhmedHanafy725** 2024-07-08 11:55 UTC
Labels: type_feature
