### ISSUE TITLE
I got `Failed to get user farms!` from `getUserNodes` in my farms page.

### ISSUE THREAD

**Issue by AlaaElattar** [threefoldtech/tfgrid-sdk-ts#1666] opened 2023-12-12 09:24 UTC
- I got this error from `getUserNodes`, which is really wierd. If the error from there, it should be `Failed to get user nodes!`. 
- Also, all farms were displayed.

![Screenshot from 2023-12-12 10-25-55](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/54944491/e549d538-ec5e-4c02-9004-d4f5e79fe1bf)

**Comment by zaelgohary** [comment] 2023-12-17 16:24
@AlaaElattar I tried multiple times on dev & qa but couldn't reproduce the error. Can you check again if you can reproduce it?

**Comment by A-Harby** [comment] 2023-12-20 15:27
I also tried with slow and offline network options but the only error I got was this error and it was handled so will close this as done.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/6944ece7-91e6-4a72-b929-dcd153790699)

**Comment by ramezsaeed** [comment] 2023-12-27 11:24
cannot reproduce.

**Closed by ramezsaeed** 2023-12-27 11:24 UTC
Labels: type_bug, playground
