### ISSUE TITLE
Deploy button enabled before checking pool storage

### ISSUE THREAD

**Issue by zaelgohary** [threefoldtech/tfgrid-sdk-ts#1300] opened 2023-10-29 11:58 UTC
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/40770501/dbb08f06-d8a5-4437-af83-4de784925545)

After some time, the button was disabled as there was no enough storage.

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/40770501/469e3c9c-a3d4-40e2-879c-8cf3506ff88c)

**Comment by 0oM4R** [comment] 2023-10-30 15:07
still investigating can't reproduce the issue i a clear way, but i think that the issue occurs on a slow connection when the grid take long time to load before validate the node's storage pool; will check tmw with alaa she had a [pr](https://github.com/threefoldtech/tfgrid-sdk-ts/pull/1305/files) related to this issue

**Comment by 0oM4R** [comment] 2023-11-01 02:39
this can be noticeable on slow connection: a delay between validating the nodeid value and validating storage pool, on that delay the nodid field is valid, which make the deploy button enabled. 
on initial case where there is no node selected, the selectedNode is undefined until the validating storage is finished, then it update the value, but on the mentioned delay if you click on the deploy button will deploy on nodeId undefined as mentioned on #1244 
Not sure what the proper solution is. I will try to fix this today isA

**Comment by 0oM4R** [comment] 2023-11-01 17:55
deploy button is working fine know, but we need to handle network errors, any error  while validating storage pool will show the error massage : `Couldn't fit the required disks in Node ${validatingNode.nodeId} storage pools, please select another node`
will check tmw if this will be in separate issue or in the same pr

**Comment by A-Harby** [comment] 2023-11-05 09:22
Verified, Devnet.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/a368c04c-f6d6-4889-8a38-ae72225a70fe)
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/6cae32d1-4d1f-4d91-beea-024ea9c94a23)

**Closed by A-Harby** 2023-11-05 09:22 UTC
Labels: type_bug, playground
