### ISSUE TITLE
Updating the balance after every transaction like before

### ISSUE THREAD

**Issue by A-Harby** [threefoldtech/tfgrid-sdk-ts#921] opened 2023-08-06 12:24 UTC
### Description

Twin TFT balance is not updated after any transaction occurs; instead, you must refresh the page or log out and log back in to see the difference in amount.

### Steps to reproduce

- Log in any twin.
- Do any transaction (Through Bridge, Transfer page or ...).
- Balance will remain the same after transaction succeeded.
- Refresh the page and the balance will be updated.

**Comment by AhmedHanafy725** [comment] 2023-08-06 13:03
duplicate of #895

**Closed by AhmedHanafy725** 2023-08-06 13:03 UTC
Labels: type_bug, dashboard
