### ISSUE TITLE
Add Automated and Manual Node Selection Radio Buttons

### ISSUE THREAD

**Issue by Mik-TF** [threefoldtech/tfgrid-sdk-ts#1452] opened 2023-11-21 19:09 UTC
parent: https://github.com/threefoldtech/home/issues/1466

Read this reply for more information: https://github.com/threefoldtech/home/issues/1466#issuecomment-1817854334

As proposed by @AhmedHanafy725. Radio buttons design by @ehab-hassan 

To improve the UI and UX of the Playground.

***

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/77026219/edf45b8b-88f1-495f-bf2c-47ee9d786d7e)

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/77026219/48188136-efed-45ac-bafb-257b5465e587)

**Comment by AhmedHanafy725** [comment] 2023-11-22 10:26
duplicate of #1094

**Closed by AhmedHanafy725** 2023-11-22 10:26 UTC
