### ISSUE TITLE
🐞 [Bug]: Dashboard stuck on the loading page

### ISSUE THREAD

**Issue by A-Harby** [threefoldtech/tfgrid-sdk-ts#2703] opened 2024-05-15 08:40 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### which package/s did you face the problem with?

Dashboard

### What happened?

The dashboard get stuck on the loading pages sometimes on devnet and localhost, it used to show the reload button but not it doesn't.

how long should it take to show that button? And does it retry more than once to load the site?

### which network/s did you face the problem on?

Dev

### version

71a3b1a

### Relevant screenshots/screen records

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/35936474-6d5f-4974-9c23-d1b5db3304ad)

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/3159f749-c7a9-4afc-9c43-7c156666c21f)

### Relevant log output

```console
.
```

**Comment by Mahmoud-Emad** [comment] 2024-05-29 11:51
Can you please provide some steps to reproduce this?

**Comment by A-Harby** [comment] 2024-05-29 12:10
> Can you please provide some steps to reproduce this?



It usually happens due to a network error, but you could try a slow 3G network in the developer tool.

**Comment by Mahmoud-Emad** [comment] 2024-05-30 07:48
I can't reproduce it, it worked with me even on a 3G network 

[Screencast from 05-30-2024 10:45:19 AM.webm](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/57001890/db436efb-cf4e-49d4-8151-8a728a86f810)

**Comment by A-Harby** [comment] 2024-06-02 15:06
> @A-Harby I can't reproduce it; it worked with me even on a 3G network
> 

@Mahmoud-Emad I'm going to close the issue as unreproducible for now, but can you clarify the timeout process?
Like, how long is the timeout duration for the reload button to be shown, and if there is a retry on failed to load, how many does it retey? so I can create a test case to make sure it's not reproducible.

**Comment by khaledyoussef24** [comment] 2024-06-05 13:59
I can not reproduce the issue shall we move it to done for now ?

**Comment by khaledyoussef24** [comment] 2024-06-09 09:59
tried to produce the issue again but could not will close it for now.

**Closed** 2024-06-09 14:41 UTC
Labels: type_bug, dashboard
