### ISSUE TITLE
Automating the new playground and dashboard tests

### ISSUE THREAD

**Issue by khaledyoussef24** [threefoldtech/tfgrid-sdk-ts#1285] opened 2023-10-25 13:14 UTC
### Description

Designing automated tests for:
- [x] new [dashboard](https://new.playground.dev.grid.tf/#/portal/twin) (explorer and portal)
- [x] adding a nightly test run to git hub actions

Using the designed test cases in testlodge for [the playground test suite](https://app.testlodge.com/a/26076/projects/40893/suites/227225) and [the dashboard test suite](https://app.testlodge.com/a/26076/projects/40893/suites/209098)

**Comment by khaledyoussef24** [comment] 2023-10-26 04:00
we have to discuss if we will use the portal or the tf-extension it will be the starting part of every test.

**Comment by khaledyoussef24** [comment] 2023-10-26 04:03
playground tests should include deployments and checking contracts and if the solutions are working correctly.

**Comment by khaledyoussef24** [comment] 2023-10-26 04:05
dashboard tests should include portal part,explorer and calculator (both simulator and pricing calc.)

**Comment by ramezsaeed** [comment] 2023-12-17 16:18
work in progress (WIP)
updated home page, profile manager, twin and transfere pages.
https://github.com/threefoldtech/tfgrid-sdk-ts/pull/1667

**Comment by xmonader** [comment] 2023-12-27 11:22
Is this still blocked?

**Comment by ramezsaeed** [comment] 2024-01-01 20:18
Not Blocked
Work in progress here: https://github.com/threefoldtech/tfgrid-sdk-ts/pull/1667

**Comment by AhmedHanafy725** [comment] 2024-02-28 15:49
what is the status here?

**Comment by ramezsaeed** [comment] 2024-02-28 15:56
will move it to 3.14

**Comment by xmonader** [comment] 2024-04-14 10:44
no update?

**Comment by A-Harby** [comment] 2024-04-14 13:50
I updated the Homepage, Profile Manager, Twin, Transfer, and Bridge test pages with new UI changes, closed the old PR https://github.com/threefoldtech/tfgrid-sdk-ts/pull/2552, and created a new PR https://github.com/threefoldtech/tfgrid-sdk-ts/pull/2552 as all the tests were deleted when the dashboard and weblets directories were removed.

The PR is drifted as the new directory has not been confirmed yet, but the tests for the pages mentioned above are ready for review.

**Comment by ramezsaeed** [comment] 2024-04-14 16:31
Lets merge this asap.

**Comment by A-Harby** [comment] 2024-05-08 15:46
I have updated PR https://github.com/threefoldtech/tfgrid-sdk-ts/pull/2552 with new changes as requested: https://github.com/threefoldtech/tfgrid-sdk-ts/pull/2552#issuecomment-2100872106.

And I'm working on the other three pages and will create a separate PR for them.

The estimated time is 2 days after finishing the current test run 2.4.0 on testnet.

**Comment by A-Harby** [comment] 2024-06-05 09:43
Done fixed, approved, and merged.

I fixed all the portal page tests in the new UI and added new cases for new features.

When the workflow runs the tests, it will keep failing in some tests:

All the farm tests will fail until these issues are fixed.
- https://github.com/threefoldtech/tfgrid-sdk-ts/issues/2578
-  https://github.com/threefoldtech/tfgrid-sdk-ts/issues/2610.
The node public config tests will fail until this issue is fixed.
- #2637.
Some tests will fail because of this issue.
- https://github.com/threefoldtech/tfgrid-sdk-ts/issues/2703.

**Closed** 2024-06-05 09:58 UTC
Labels: type_story
