### ISSUE TITLE
Update discounts tooltip in dedicated table

### ISSUE THREAD

**Issue by zaelgohary** [threefoldtech/tfgrid-sdk-ts#799] opened 2023-07-11 15:24 UTC
Discounts have been changed as per [billing URL](https://manual.grid.tf/dashboard/portal/dashboard_portal_dedicated_nodes.html#billing--pricing)

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/40770501/33009d6f-2e99-4458-afc7-0dc7ca2f98f8)

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/40770501/bd7b00d2-1801-4a12-b31d-49ead93fbd2c)

**Comment by ramezsaeed** [comment] 2023-07-17 08:45
@mohamedamer453 
please review docs and real current discount.

**Comment by mohamedamer453** [comment] 2023-07-17 10:22
The tooltip is displaying the correct discount for dedicated nodes and it can be confirmed from [these](https://gist.github.com/mohamedamer453/6ac5cdac2fb35bbf3d1462e89c8bb1e7#rent-contract) calculations in comparison to the actual price for the node.

![image](https://github.com/threefoldtech/info_grid/assets/101194226/eca1817f-cd35-456c-b65a-f1b1f9fe6c2a)

so the issue is with the value in the manual as it should be `50%` not `70%` so i created a separate issue for it and will fix it asap https://github.com/threefoldtech/info_grid/issues/189. and it's safe to close this one since the tooltip is displaying the correct value.

**Closed by mohamedamer453** 2023-07-17 10:22 UTC
Labels: type_bug, dashboard
