### ISSUE TITLE
🐞 [Bug]: CapRover Dashboard App: Details of Workers disappear after few seconds

### ISSUE THREAD

**Issue by mik-tf** [threefoldtech/tfgrid-sdk-ts#3281] opened 2024-08-09 16:03 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### which package/s did you face the problem with?

Dashboard

### What happened?

- When deploying, e.g. 1 leader, 2 workers, I can see the details of the 3 nodes in JSON table, but the Details page shows the 3 nodes for a few seconds then only the leader node is shown
- Also it is neither shown on the table page (can only see the leader node on the summary table under the deployment tabs)
   -  it only shows the leader, then if you delete the leader, it shows the worker1, then, etc. to worker 2 
- Screenshots to show this below

### Steps To Reproduce

1. deploy worker + 2 leaders note
2. after deployment check the Details page
3. It changes to only showing leader after some time

### which network/s did you face the problem on?

Main

### version

Latest

### Relevant screenshots/screen records

![image](https://github.com/user-attachments/assets/9c26dc48-2666-47ce-b04a-22a2d919be1c)

![image](https://github.com/user-attachments/assets/5ee6d68f-e962-4bd7-a119-48000488a0d7)

- If I delete leader 1 and worker 1, I see worker 2 in the table. In brief, we should show all worker 1,2 and leader 1 in the table here OR access worker 1,2 and leader 1 on the leader 1 details page.

![image](https://github.com/user-attachments/assets/099b6bef-e7e7-44c4-8c57-c4f63dd23fee)

### Relevant log output

```console
{
  "version": 0,
  "contractId": 47003,
  "nodeId": 20,
  "name": "leader1",
  "created": 1723218864,
  "status": "ok",
  "message": "",
  "flist": "https://hub.grid.tf/tf-official-apps/tf-caprover-latest.flist",
  "publicIP": {
    "ip": "185.206.122.151/24",
    "ip6": "",
    "gateway": "185.206.122.1"
  },
  "planetary": "300:a038:4456:dba6:c5c4:3f0e:cb08:1f32",
  "myceliumIP": "568:c45b:bfd:fdf6:ff0f:0:400:2",
  "interfaces": [
    {
      "network": "nwhrn1a",
      "ip": "10.20.4.2"
    }
  ],
  "capacity": {
    "cpu": 1,
    "memory": 2048
  },
  "mounts": [
    {
      "name": "data0",
      "mountPoint": "/var/lib/docker",
      "size": 53687091200,
      "state": "ok",
      "message": ""
    }
  ],
  "env": {
    "SWM_NODE_MODE": "leader",
    "CAPROVER_ROOT_DOMAIN": "threefold.pro",
    "CAPTAIN_IMAGE_VERSION": "latest",
    "PUBLIC_KEY": "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDVRwvsIUUudUJt+DvzX/Jre2hAHS2Y1HDutbe6vxK5Hnr9QoA7iKuTjqcRu9yDR2mN/JFHFIef7nFiXNjERbISqrFK4HIaFLHXuJaGMbUj7Bl3d1g5xGYeDtgh6+rmgeKvxauopY/VwGKVcZ83UYmT6ffkJRCgCqbrVzvfKJUNvucehZPpELcwbVSk3yNmqX+n3twuVsvoyH/m6D6DxiBrbQ0HfW1nDPp4AVfD7cn1fyNOleuHp9vvHy970a+2K5/fpU62sFLDAlvjpKBHaheAPdY+Sck7MfNlSrzAlt1+VSGnj8MsSvcdV1CAdc7muus77o59aIquUxwCfBLfeI85WBLQ63EsafDmkHeF7sJ90Jq5gnzX++fhgAySMFUJKX30HlWJhPCQTaEMSbXkrbqJGchoeY6fH/CWhiBmuZDTe5JOLbpKvSrVz91asD7+mIl+/CFLGwSgilzty+zwgmdlR5PAfK9oiA+cxorZmSu/S7iZv5+rB+mSXbvVONa+LDk= pcone@pcone-computer",
    "DEFAULT_PASSWORD": "10iRQIiS2n",
    "CAPTAIN_IS_DEBUG": "true"
  },
  "entrypoint": "/sbin/zinit init",
  "metadata": "",
  "description": "",
  "rootfs_size": 524288000,
  "corex": false,
  "gpu": [],
  "deploymentName": "leader1",
  "projectName": "caprover/leader1",
  "billing": "No Data Available",
  "wireguard": "[Interface]\nAddress = 100.64.20.3/32\nPrivateKey = ktGQ1KdWvc3h6PpPGrtXVt7EFYsVkO3lOkQYOMZiiyg=\n\n[Peer]\nPublicKey = FnRcXFvMjDU4Do9R0JbdxDHYz2f9q1uTcQtc60eeqG4=\nAllowedIPs = 10.20.0.0/16, 100.64.20.0/32\nPersistentKeepalive = 25\nEndpoint = 185.206.122.131:21837",
  "workers": [
    {
      "version": 0,
      "contractId": 47005,
      "nodeId": 5,
      "name": "work1",
      "created": 1723218869,
      "status": "ok",
      "message": "",
      "flist": "https://hub.grid.tf/tf-official-apps/tf-caprover-latest.flist",
      "publicIP": {
        "ip": "185.206.122.155/24",
        "ip6": "",
        "gateway": "185.206.122.1"
      },
      "planetary": "300:9c4a:29ac:6e0b:c0de:8c84:779b:7c87",
      "myceliumIP": "4e9:c850:c016:888c:ff0f:0:500:2",
      "interfaces": [
        {
          "network": "nwhrn1a",
          "ip": "10.20.5.2"
        }
      ],
      "capacity": {
        "cpu": 1,
        "memory": 2048
      },
      "mounts": [
        {
          "name": "data0",
          "mountPoint": "/var/lib/docker",
          "size": 53687091200,
          "state": "ok",
          "message": ""
        }
      ],
      "env": {
        "SWM_NODE_MODE": "worker",
        "PUBLIC_KEY": "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDVRwvsIUUudUJt+DvzX/Jre2hAHS2Y1HDutbe6vxK5Hnr9QoA7iKuTjqcRu9yDR2mN/JFHFIef7nFiXNjERbISqrFK4HIaFLHXuJaGMbUj7Bl3d1g5xGYeDtgh6+rmgeKvxauopY/VwGKVcZ83UYmT6ffkJRCgCqbrVzvfKJUNvucehZPpELcwbVSk3yNmqX+n3twuVsvoyH/m6D6DxiBrbQ0HfW1nDPp4AVfD7cn1fyNOleuHp9vvHy970a+2K5/fpU62sFLDAlvjpKBHaheAPdY+Sck7MfNlSrzAlt1+VSGnj8MsSvcdV1CAdc7muus77o59aIquUxwCfBLfeI85WBLQ63EsafDmkHeF7sJ90Jq5gnzX++fhgAySMFUJKX30HlWJhPCQTaEMSbXkrbqJGchoeY6fH/CWhiBmuZDTe5JOLbpKvSrVz91asD7+mIl+/CFLGwSgilzty+zwgmdlR5PAfK9oiA+cxorZmSu/S7iZv5+rB+mSXbvVONa+LDk= pcone@pcone-computer"
      },
      "entrypoint": "/sbin/zinit init",
      "metadata": "",
      "description": "",
      "rootfs_size": 524288000,
      "corex": false,
      "gpu": [],
      "deploymentName": "leader1",
      "projectName": "caprover/leader1",
      "billing": "No Data Available",
      "wireguard": "[Interface]\nAddress = 100.64.20.3/32\nPrivateKey = ktGQ1KdWvc3h6PpPGrtXVt7EFYsVkO3lOkQYOMZiiyg=\n\n[Peer]\nPublicKey = FnRcXFvMjDU4Do9R0JbdxDHYz2f9q1uTcQtc60eeqG4=\nAllowedIPs = 10.20.0.0/16, 100.64.20.0/32\nPersistentKeepalive = 25\nEndpoint = 185.206.122.131:21837"
    },
    {
      "version": 0,
      "contractId": 47006,
      "nodeId": 1,
      "name": "work2",
      "created": 1723218871,
      "status": "ok",
      "message": "",
      "flist": "https://hub.grid.tf/tf-official-apps/tf-caprover-latest.flist",
      "publicIP": {
        "ip": "185.206.122.156/24",
        "ip6": "",
        "gateway": "185.206.122.1"
      },
      "planetary": "300:2589:76ee:f44e:ce6e:7a22:e0b5:169d",
      "myceliumIP": "588:b6c9:bec0:1dbf:ff0f:0:200:2",
      "interfaces": [
        {
          "network": "nwhrn1a",
          "ip": "10.20.2.2"
        }
      ],
      "capacity": {
        "cpu": 1,
        "memory": 2048
      },
      "mounts": [
        {
          "name": "data0",
          "mountPoint": "/var/lib/docker",
          "size": 53687091200,
          "state": "ok",
          "message": ""
        }
      ],
      "env": {
        "SWM_NODE_MODE": "worker",
        "PUBLIC_KEY": "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDVRwvsIUUudUJt+DvzX/Jre2hAHS2Y1HDutbe6vxK5Hnr9QoA7iKuTjqcRu9yDR2mN/JFHFIef7nFiXNjERbISqrFK4HIaFLHXuJaGMbUj7Bl3d1g5xGYeDtgh6+rmgeKvxauopY/VwGKVcZ83UYmT6ffkJRCgCqbrVzvfKJUNvucehZPpELcwbVSk3yNmqX+n3twuVsvoyH/m6D6DxiBrbQ0HfW1nDPp4AVfD7cn1fyNOleuHp9vvHy970a+2K5/fpU62sFLDAlvjpKBHaheAPdY+Sck7MfNlSrzAlt1+VSGnj8MsSvcdV1CAdc7muus77o59aIquUxwCfBLfeI85WBLQ63EsafDmkHeF7sJ90Jq5gnzX++fhgAySMFUJKX30HlWJhPCQTaEMSbXkrbqJGchoeY6fH/CWhiBmuZDTe5JOLbpKvSrVz91asD7+mIl+/CFLGwSgilzty+zwgmdlR5PAfK9oiA+cxorZmSu/S7iZv5+rB+mSXbvVONa+LDk= pcone@pcone-computer"
      },
      "entrypoint": "/sbin/zinit init",
      "metadata": "",
      "description": "",
      "rootfs_size": 524288000,
      "corex": false,
      "gpu": [],
      "deploymentName": "leader1",
      "projectName": "caprover/leader1",
      "billing": "No Data Available",
      "wireguard": "[Interface]\nAddress = 100.64.20.3/32\nPrivateKey = ktGQ1KdWvc3h6PpPGrtXVt7EFYsVkO3lOkQYOMZiiyg=\n\n[Peer]\nPublicKey = FnRcXFvMjDU4Do9R0JbdxDHYz2f9q1uTcQtc60eeqG4=\nAllowedIPs = 10.20.0.0/16, 100.64.20.0/32\nPersistentKeepalive = 25\nEndpoint = 185.206.122.131:21837"
    }
  ]
}
```

**Comment by Mahmoud-Emad** [comment] 2024-08-19 11:09
Check the load deployments in the node deployment list

**Comment by Mahmoud-Emad** [comment] 2024-09-03 10:11
During the navigation, I found some extra issues

1. The Caprover listing isn't working as expected which is reported in this issue.
2. When attaching a new worker we expect to add it to the same cluster, what happens is right, but we're not doing a watch on it. after adding it I found that it's not listed out, even with the fix of the first point.
3. The delete button doesn't behave as it should, I deployed a Caprover leader and 2 workers, and then I pressed the delete button, I expected to delete all of the cluster leader and workers, but what happened is that it deleted only the leader and after that it listed the first worker then after deleting it, it listed the second worker as well as it shouldn't happen.



[Screencast from 09-03-2024 01:49:58 PM.webm](https://github.com/user-attachments/assets/da3bb923-d610-4985-b7ab-3527c5389c1a)

**Comment by Mahmoud-Emad** [comment] 2024-09-04 07:08
The listing issue is fixed in the mentioned PR, However, there is another issue with deleting all of the cluster

**Comment by Mahmoud-Emad** [comment] 2024-09-04 07:12
I believe displaying a message to users, informing them that their deployment contains 'leader/workers' and requesting confirmation before deleting all of the cluster, would be helpful. This is the current behavior.

![image](https://github.com/user-attachments/assets/51593928-7848-4744-b01d-f7d4474a3c57)

**Comment by Mahmoud-Emad** [comment] 2024-09-22 09:42
## Issue update

### Work done
**Fix Caprover listing**

#### Changes
- Push the master into the first index of the result array
- Push the workers into the master, second index of the result array
- Tested the code well

**Comment by Mahmoud-Emad** [comment] 2024-09-26 07:59
> However, there is another issue with deleting all of the cluster

This one also should be fixed in the mentioned PR

**Comment by Mahmoud-Emad** [comment] 2024-10-17 11:24
## Issue update

Some issues were found while applying the fix


### Changes
- Ensure that workers are correctly removed from the deployment list when the leader is deleted to maintain data integrity.
- Merged the latest changes from the development branch to keep the codebase up to date.
- Conducted thorough testing to verify the complete functionality and ensure no regressions were introduced.

### Test Scenarios

1. Deploy `leader`, and `worker`, Go go to the contracts page and delete the deployed `leader`.
2. Deploy `leader`, attach a `worker` to it then delete the whole cluster just in time without refreshing the page.
3. Deploy `leader`, and `worker`, delete the deployed `worker` and attach another, then delete the whole cluster just in time without refreshing the page.
4. Deploy a cluster with 1 leader and 2 workers check the deployment listing dialog and make sure all of them are listed
3. Delete a cluster with the leader and more than 3 workers and make sure all of them are deleted.

**Comment by 0oM4R** [comment] 2024-10-29 09:32
reopened due: https://github.com/threefoldtech/tfgrid-sdk-ts/pull/3543#issuecomment-2443669305

**Comment by Mahmoud-Emad** [comment] 2024-11-11 09:00
Due to https://github.com/threefoldtech/tfgrid-sdk-ts/pull/3543#pullrequestreview-2401254503 the listing is working fine now, however, there is an issue with deleting the Caprover cluster reported in https://github.com/threefoldtech/tfgrid-sdk-ts/pull/3543#issuecomment-2443669305 


https://github.com/threefoldtech/tfgrid-sdk-ts/issues/3614

**Comment by A-Harby** [comment] 2024-11-11 13:19
Devnet 1ea3613.

I deployed a caprover leader with 2 worekers, and they were listed.
![image](https://github.com/user-attachments/assets/709d250b-d0e5-4d0b-9d7f-ac50da390711)
Then I deployed 2 more workers, and none of them were listed either on manage worker or on deployment details!!
![image](https://github.com/user-attachments/assets/040d7822-07f7-45f2-bdda-95f7b109db0f)
![image](https://github.com/user-attachments/assets/e193ada5-b82a-4c30-a8c7-bdf4328a0685)
![image](https://github.com/user-attachments/assets/0236772a-0ba6-4bb3-b816-202d63ee89c6)
![image](https://github.com/user-attachments/assets/3563fae4-cff6-4f1d-bf9c-6f956c89e79b)

**Comment by 0oM4R** [comment] 2024-11-19 03:40
Issue update:
i can't rerpduce any issue mentioned in the comments, listing and deleteing are working as expected

**Comment by 0oM4R** [comment] 2024-11-20 15:54
Issue update: 

working on inhancing delete proccess, by using `Machines.delete` but it can't delete the workers, will keep investigating

**Comment by 0oM4R** [comment] 2024-11-21 19:03
Issue update: inhanced the deleting proccess, working on listing caprover deployments, anyways if the leader contract is missing we have the warning message 
![image](https://github.com/user-attachments/assets/6e418f1f-c071-460d-b4b0-724d7814ed1f)

**Comment by 0oM4R** [comment] 2024-11-24 13:37
No related changes on done to this issue, will move it to verification to verifiy all caprover listig-related scenarios 
changes will be on #3614

**Comment by atefnazmy** [comment] 2024-12-02 07:15
-Verified on Dev,
-Version: 4e2fc0b
- All workers' details are still visible even after many hours since deployment.

![Image](https://github.com/user-attachments/assets/4d1a68c2-755b-424f-9160-996b70cec708)

**Closed as completed** 2024-12-02 12:52 UTC
Labels: type_bug, dashboard
