### ISSUE TITLE
Can't remove public config

### ISSUE THREAD

**Issue by scottyeager** [threefoldtech/tfgrid-sdk-ts#498] opened 2023-06-07 19:56 UTC
The option to remove a public config from a node is greyed out:

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/17682591/97e07022-e059-4da4-b394-c68b66976fbb)

The data seen in the fields was filled automatically based on the public config previously set, so the presence of a public config is recognized.

**Comment by zaelgohary** [comment] 2023-06-15 14:49
Still investigating.

**Comment by zaelgohary** [comment] 2023-06-19 09:16
The issue couldn't be reproduced. I created a public config and the remove config button was not disabled as seen below.

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/40770501/8d53f7ad-1ede-48ff-9fc8-ad7b16a52435)

Note: I tried to create a config with only ipv4 & gw4 and the save button was disabled.

**Comment by zaelgohary** [comment] 2023-06-19 09:25
Tried again with a different account:

![photo_5800814845120068963_x](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/40770501/2c0697ad-0e45-4729-96e6-bb742c222b61)

**Comment by scottyeager** [comment] 2023-06-19 18:11
So it seems the issue is with existing configs that have ipv4 only. You can test this case by adding such a config to TF Chain through another means such as Polkadot UI.

**Comment by zaelgohary** [comment] 2023-06-20 11:01
The config [here](https://github.com/threefoldtech/tfgrid-sdk-ts/issues/498#issuecomment-1596832481) was created in Polkadot and the button is active as seen in the screenshot. Which network are you using?

**Comment by scottyeager** [comment] 2023-06-20 17:46
Ah, I see now. It wasn't clear to me if the config in the second screenshot was saved.

This is seen on mainnet. One farmer reported it initially and then I reproduced it on my account.

**Comment by mohamedamer453** [comment] 2023-06-21 07:59
I've tested multiple scenarios but i wasn't able to reproduce this issue, the scenarios that i tried are:

- Added only ipv4/gw4 from polkadot UI

   ![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/101194226/7631c34f-6766-4950-af92-5be5b20f9e2e)

- Added full config from the dashboard.

   ![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/101194226/6249c871-5dcc-4737-a9e7-e9c9fc576772)

- Added config from the dashboard without ipv6

   ![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/101194226/8d68b6f5-d377-48f5-8d40-74186ba8731b)

I'll close this issue since it wasn't reproducible but if there're clear steps on how to reproduce please add it and reopen the issue.

**Closed by mohamedamer453** 2023-06-21 07:59 UTC
Labels: type_bug, dashboard
