### ISSUE TITLE
🐞 [Bug]: dashboard, peertube "incorrect username or password" while tf connect app says it works

### ISSUE THREAD

**Issue by Mik-TF** [threefoldtech/tfgrid-sdk-ts#2799] opened 2024-05-28 14:37 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### which package/s did you face the problem with?

Dashboard

### What happened?

Deploying on mainnet, or devnet, the dashboard app peertube, I use the tf connect app login button, properly sign in with tf connect, tf connect screens says "success", but peertube then says: "incorrect username or password".

### Steps To Reproduce

1. mainnet dashboard deploy peertube basic
2. access website
3. click on tf connect login
4. click proper symbol on tf connect app
5. tf connect app says success
6. peertube says incorrect username or password

### which network/s did you face the problem on?

Main

### version

latest

### Relevant screenshots/screen records

- peertube incorrect
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/77026219/3bd0c243-1158-40b5-87b3-8dd97eb1e120)

- tf connect success
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/77026219/79cbc1a9-a2c2-42dd-83ba-616358cf7786)

### Relevant log output

```console
- Incorrect username or password.
```

**Comment by ramezsaeed** [comment] 2024-06-03 11:23
Cannot reproduce;
@Mik-TF  will close it for now, and please if you faced it again Re-open it.

**Closed by ramezsaeed** 2024-06-03 11:23 UTC
Labels: type_bug

**Comment by Mik-TF** [comment] 2024-06-03 18:50
I tested on my end and it works. Thanks.
