### ISSUE TITLE
Dedicaded node section on next.dashboard.grid.tf page access

### ISSUE THREAD

**Issue by Mik-TF** [threefoldtech/tfgrid-sdk-ts#2299] opened 2024-03-03 00:59 UTC
# Situation: Dedicaded node section on next.dashboard.grid.tf page access

From telegram farmers/users ([here](https://t.me/threefoldfarmers/70012) and [here](https://t.me/threefoldfarmers/70012)), (1)  can't go to next page on dedicated nodes and (2) can't change the amount of nodes shown on one page

**Comment by AhmedHanafy725** [comment] 2024-03-03 07:45
duplicate of #2237

**Closed by AhmedHanafy725** 2024-03-03 07:45 UTC
