### ISSUE TITLE
Table pagination is not working on the farm IPs

### ISSUE THREAD

**Issue by A-Harby** [threefoldtech/tfgrid-sdk-ts#2368] opened 2024-03-06 21:05 UTC
### Description

A clear description of the bug is:

I added more than 25 IPs to that farm, but I couldn't list all of them using the rows per page, nor could I navigate through the pages, making the table only show you the first 10 IPs, and the rest aren't usable.

It also keeps collapsing the farm whenever I change the rows per page.

Must include any relevant identifiers, like:

- **Network**: Testnet and devnet

- **Version**: 2.3.0-rc3

- **Twin ID**: 586

- **Farm ID**: 365

### Steps to reproduce

1. Navigate to the dashboard.
2. Connect your wallet.
3. If you don't have a farm, create one.
4. Add more than 20 IPs (range IP would help with that).
5. Try changing the rows per page to more or less IPs.
6. Try to navigate to the next page.

### Logs/Alerts

Must include, if available:

Screenshots or screen records.

[screen-capture (15).webm](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/1ebd0d22-4d72-40e5-9a11-02e43ce60ef2)

**Comment by Mahmoud-Emad** [comment] 2024-03-07 11:43
## Issue Update

### Investigation and Solution:

Upon further investigation, it has been determined that the issue is not directly associated with the farm table. The farm table successfully lists the farms and dynamically updates the displayed farms based on the pagination selection. Therefore, the issue is unrelated to the functionality of the farm table.

However, a separate issue has been identified concerning the length of the IPs. Despite utilizing the `IP range` feature and adding `16` IPs, only `10` IPs are currently visible. This behavior is inconsistent with the expected functionality.

To address this issue, a thorough examination will be conducted to identify the root cause. Regular updates will be provided as the investigation progresses, ensuring that any findings and solutions are communicated promptly. Your patience is appreciated as we work to resolve this matter.

**Comment by Mahmoud-Emad** [comment] 2024-03-07 12:03
## Issue Update

### Investigation and Solution:

Upon closer examination, the issue was identified in the listing of IPs. While more than 10 IPs were retrieved from the chain, the `v-data-table` was only handling 10 items due to the pagination constraints of the IPs table. Additionally, it was observed that the pagination controls were intentionally hidden by overriding the table's `bottom` section through slot access.

To address these issues, the following steps will be taken:

1. The override of the table's `bottom` section, which hides the pagination controls, will be removed to restore their visibility.

2. The configuration of the `v-data-table` component will be revised and optimized to accommodate the complete list of IPs.

3. A listener will be introduced to monitor the `page` event, ensuring that the displayed items are dynamically updated as the user navigates through the paginated data.

**Comment by Mahmoud-Emad** [comment] 2024-03-07 12:10
## Issue Update

### Work done

- Removed the override on the table's bottom section to restore visibility of pagination controls.
- Revised and optimized the configuration of the v-data-table to handle the complete list of IPs.
- Introduced a listener for the page event to ensure dynamic updates as users navigate through paginated data.

### Screenshots/Video

- ![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/57001890/07f20e89-91e7-4f1b-8b67-7830efbfaefd)

  [Screencast from 03-07-2024 02:08:24 PM.webm](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/57001890/a8252786-ba04-429d-8430-049622af8f65)

**Comment by A-Harby** [comment] 2024-03-10 16:53
Devnet, 17fffef
The items per page are working correctly, but the pagination is still not working.
 
[screen-capture (18).webm](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/47bbfa5e-a117-4fd9-bb1c-b02c93ff3e31)

**Comment by A-Harby** [comment] 2024-03-11 11:01
Table sorting is not working.

[screen-capture (19).webm](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/4d6ec85d-c540-4ca0-bfb5-51e3dd9417dd)

**Comment by A-Harby** [comment] 2024-03-11 11:27
Verified, Devnet d965ce4.
The farm IPs now have a table that can list all the IPs, change items per page, and paginate through it.

[TC2636 - Farm IPs table](https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=426668#case_4233286)

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/85d9ba25-67f2-49b9-8ec2-2ecc75b2f1d9)

I created a separate [issue](https://github.com/threefoldtech/tfgrid-sdk-ts/issues/2390) for the sorting.

**Closed** 2024-03-13 16:56 UTC
Labels: type_bug, dashboard
