### ISSUE TITLE
Mattermost Instances table stuck on loading

### ISSUE THREAD

**Issue by A-Harby** [threefoldtech/tfgrid-sdk-ts#1984] opened 2024-01-15 12:36 UTC
### Description

Devnet, b43ea4c.

- **Twin ID** : 162.
- Can't get any of the deployment details (node or farm ID).

The loading deployment stuck forever, giving me this error on the console.

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/2c1fdacf-b2b5-4dae-baca-9a6a2d8a2847)

At least there should be a warning to the user to reload or notify him that there is an issue.

### Steps to reproduce

1. Navigate to the Dashboard.
2. Connect your wallet.
3. Deploy some instance of the mattermost.
4. List the deployment in the mattermost.

**Comment by AlaaElattar** [comment] 2024-01-17 11:50
- should be flagged as alpha here https://github.com/threefoldtech/tfgrid-sdk-ts/issues/2021

**Comment by zaelgohary** [comment] 2024-02-12 09:32
Couldn't reproduce. Will move to verification.

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/40770501/82b338e6-9613-4be7-8b07-43f3b80af1bc)

**Comment by zaelgohary** [comment] 2024-02-12 09:39
I was able to see the error in the console but the error was handled as seen below.

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/40770501/08f2721a-a201-4425-a9d1-9554ad168a99)

**Comment by khaledyoussef24** [comment] 2024-03-25 10:34
version : 385928e
network : devnet

verified listing mattermost deployments now working fine
![Screenshot 2024-03-25 at 12 33 00 PM](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/5c397d56-b0c8-42dc-bb24-9b28c21b1c95)
https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=422332#case_4150343

**Comment by ramezsaeed** [comment] 2024-03-31 22:54
Verified:
- Devnet
- d2d2622

mattermost marked as alpha

![Screenshot from 2024-04-01 00-53-59](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/16083592/ad0fb25e-d6c5-4bc0-945c-017d85508b17)

**Closed by ramezsaeed** 2024-03-31 22:54 UTC
Labels: type_bug, playground
