### ISSUE TITLE
Explorer: `ID` & `Name` sorting are not working in the `Farms` table

### ISSUE THREAD

**Issue by mohamedamer453** [threefoldtech/tfgrid-sdk-ts#45] opened 2023-04-03 07:15 UTC
### Description

The Sorting functionality for the farms table is not working.

[Screencast from 03-04-23 09:06:53.webm](https://user-images.githubusercontent.com/101194226/229436437-9107172c-3a55-4e6f-8018-1b13cbf1f66d.webm)

### Steps to reproduce

- Navigate to https://dashboard.dev.grid.tf/explorer/farms
- Try to sort the `ID` or `Name` column.

### Environment 

- Network: `Devnet`
- Dashboard Version: `v1.4.0-rc10`

### Logs

- No logs or errors were returned in the console as seen above.

**Comment by 0oM4R** [comment] 2023-08-20 15:40
I tried to rewrite the table section, and it worked fine until I added `:server-items-length="farms.total"`
I believe that we should implement external sorting. The object `sort` is used to check if the sort parameters have changed or not in the update function, but no sorting happens to the result.
I will wait for Rabie to check exactly where the issue is.

**Comment by zaelgohary** [comment] 2023-11-05 11:41
Should be done once https://github.com/threefoldtech/tfgrid-sdk-ts/pull/1240 is merged.

**Comment by A-Harby** [comment] 2023-12-06 12:51
Sorting now only sorts the farms on the page loaded itself, not all the farms.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/53c8960c-3d7f-4167-8053-bf3d59f8f951)

**Comment by amiraabouhadid** [comment] 2023-12-13 11:38
@A-Harby you can't sort all farms because the gridproxy imposes a limit of 50 farms on the query.

**Comment by AhmedHanafy725** [comment] 2023-12-14 08:45
sorting is still not supported and we should disable the sorting on the table.

**Comment by zaelgohary** [comment] 2023-12-14 09:00
@amiraabouhadid Sorting is now supported from [Proxy](https://github.com/threefoldtech/tfgrid-sdk-go/issues/350#issuecomment-1793750860) side. For now, we can disable sorting in ALL nodes/farms tables. And we'll work on them in 314 [here](https://github.com/threefoldtech/tfgrid-sdk-ts/issues/1685)

**Comment by A-Harby** [comment] 2023-12-19 15:41
Verified,
Devnet, c9a726e.

Sorting is now disabled on all tables (farms, nodes, dedicated nodes, your farms, and your nodes).
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/2702ddf5-b7bd-4965-95eb-631b3c8c4f63)
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/49df2b7e-04b0-4fa3-833b-e3e3ccc506f9)
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/8ddb337f-5fb6-45e5-bd09-09ee5da14099)
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/a555a168-b438-4258-a81e-62a254a79dbe)
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/e3230914-d6b9-4aaa-b4f3-2b52e97bdc0c)

[TC2213 - Farm Nodes Table Sorting (SKIP)](https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=422339#case_4150422)
[TC2221 - Dedicated Nodes Table Sorting (SKIP)](https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=422339#case_4150430)
[TC2242 - Farms Table Sorting (SKIP)](https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=422339#case_4150451)
[TC2254 - Nodes Table Sorting (SKIP)](https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=422340#case_4150463)
[TC2272 - Farms Table Sorting (Skip)](https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=422340#case_4150481)
[TC2281 - Farms Nodes table: status sorting (SKIP)](https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=422340#case_4150490)

**Closed** 2023-12-24 11:25 UTC
Labels: dashboard
