### ISSUE TITLE
Node GPU data hangs

### ISSUE THREAD

**Issue by samaradel** [threefoldtech/tfgrid-sdk-ts#2039] opened 2024-01-18 14:22 UTC
node ```6230``` has 3 GPUs on mainnet but the value is hanging 

[Screencast from 18-01-24 16:09:01.webm](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/11662805/68cb2836-285c-435a-8229-b11fa63f80e2)

when it hangs clear button doesn't work.

[Screencast from 18-01-24 15:42:28.webm](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/11662805/1489a9b8-d2c2-4c94-9049-83c1c38e97fe)

**Comment by AlaaElattar** [comment] 2024-01-22 11:05
duplicate of #2059

**Closed** 2024-01-28 11:49 UTC
Labels: type_bug, playground
