### ISSUE TITLE
🐞 [Bug]: Billing isn't reflected on the dashboard contracts

### ISSUE THREAD

**Issue by A-Harby** [threefoldtech/tfgrid-sdk-ts#3406] opened 2024-09-12 14:07 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### which package/s did you face the problem with?

Dashboard

### What happened?

I noticed that some of my contracts get delayed showing the billing value after a full billing cycle if it didn't show it at all.

Its billed on the TFChain and its showing the on chain and graphql.

### which network/s did you face the problem on?

Dev

### version

a948bfa

### Twin ID/s

9090

### Node ID/s

250

### Farm ID/s

1

### Contract ID/s

151438

### Relevant screenshots/screen records

![image](https://github.com/user-attachments/assets/dcbd9849-68c1-4089-962b-ce6e5069a374)

[dashboard (2).log](https://github.com/user-attachments/files/16980664/dashboard.2.log)

### Relevant log output

```console
{
  "contract_id": 151438,
  "twin_id": 9090,
  "type": "rent",
  "state": "Created",
  "created_at": 1726144326,
  "details": {
    "nodeId": 250,
    "farm_id": 1
  },
  "solutionName": "-",
  "solutionType": "-",
  "expiration": "-",
  "consumption": 0
}


{
  standardReserve: 17,937,800
  additionalReserve: 0
  standardOverdraft: 0
  additionalOverdraft: 0
  lastUpdatedSeconds: 1,726,147,368
  cycles: 1
}


with amount 17,937,800
```

**Comment by zaelgohary** [comment] 2024-09-18 09:56
The issue is with the created_at interface. Once fixed, the billing will be fixed.

**Comment by amiraabouhadid** [comment] 2024-09-18 09:57
problem in first time created billing report because billing rate is calculated by subtracting current from previous report

**Comment by zaelgohary** [comment] 2024-09-18 09:57
The issue happens in the first billing cycle only.

**Comment by 0oM4R** [comment] 2024-10-01 12:52
I couldn't find the created_at interface issue but found that the issue is with accessing the contract field in the gql response 
![image](https://github.com/user-attachments/assets/644868c7-6623-4a6b-b738-1f75e115de7a)

so we need to update the `GqlConsumption` interface

**Comment by khaledyoussef24** [comment] 2024-11-04 07:10
verified on devnet
Version ffbb750

Billing is now reflected right on the dashboard
deployment list : 
![Image](https://github.com/user-attachments/assets/81d5fa25-d04d-4f92-aa3d-fd2eb3fc1ecb)
![Image](https://github.com/user-attachments/assets/94e6232a-b8dd-4df7-af2a-f0009d253889)
contracts list : 
![Image](https://github.com/user-attachments/assets/dfc4b177-20fc-4bf0-8886-37b0a59a067a)
![Image](https://github.com/user-attachments/assets/62dd743f-e4a4-463c-a5fb-ce8d0ccc6eaf)
only network contracts is showing no data available

[testcase](https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=430129#case_4410343)

**Closed as completed** 2024-11-04 09:04 UTC
Labels: type_bug, dashboard
