### ISSUE TITLE
🐞 [Bug]: No error shown if the dashboard couldn't load the domains workloads

### ISSUE THREAD

**Issue by AhmedHanafy725** [threefoldtech/tfgrid-sdk-ts#3389] opened 2024-09-08 12:00 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### which package/s did you face the problem with?

Dashboard

### What happened?

The gateway node is down and no error is shown to tell the user that he has workloads but couldn't load it

### Steps To Reproduce

- Deploy a vm
- Attach a domain workload to this vm
- Throw an error manually while loading the domain

### which network/s did you face the problem on?

Dev

### version

development

### Relevant screenshots/screen records

![image](https://github.com/user-attachments/assets/9425facc-557d-4e3b-96ee-936998eec56f)

![image](https://github.com/user-attachments/assets/e05f933b-3196-46b1-bb1a-ad8b75b44efd)

### Relevant log output

```console
-
```

**Comment by zaelgohary** [comment] 2024-09-18 09:38
Show warning for the user in case of error while listing.

**Comment by A-Harby** [comment] 2024-11-03 16:13
After list failed and reload, the error dialog is shown for no error!.

![image](https://github.com/user-attachments/assets/135f25d8-62d8-4a13-99ad-3f0c958dfc6f)
![image](https://github.com/user-attachments/assets/295706b2-086f-48ed-a2bc-d139836d713e)
![image](https://github.com/user-attachments/assets/a219a258-d0bf-4a6d-a520-2b129b1aac0a)


Updated test case: [TC2157 - domain deployment list](https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=422333#case_4150366)

**Comment by khaledyoussef24** [comment] 2024-11-05 12:15
the issue is still reproducible on devnet
i made a domain deployment fail by closing the internet connection in the creation phase
![Image](https://github.com/user-attachments/assets/790b7fb7-d4f6-4996-98dc-a979618a9df1)
after the issue i could not load any old deployed domain in the domain list
![Image](https://github.com/user-attachments/assets/b7c61fbd-a156-442e-9f0e-50954ba0280e)

**Comment by amiraabouhadid** [comment] 2024-11-11 09:05
could not reproduce 
after disconnecting and reconnecting network on devnet, it behaves correctly. 
![Image](https://github.com/user-attachments/assets/8b50d630-427c-4ebd-a2bc-4e2ea389f647)
original issue was for listing domains not when creating domains. Nevertheless, error message was added for network error on domain creation
![Image](https://github.com/user-attachments/assets/ac1ffd40-50e8-4e8b-966a-8175422c1a62)
was able to view domain list even after domain creation failed
![Image](https://github.com/user-attachments/assets/a5fa8658-ba44-4486-82b0-698b0e97bd22)

**Comment by khaledyoussef24** [comment] 2024-11-11 15:23
could not produce any more
may be node was down working fine now

![Image](https://github.com/user-attachments/assets/b6a43460-69a9-4632-ad87-6f5ba6b58650)
![Image](https://github.com/user-attachments/assets/9c6673f5-0c5a-4b7a-86a4-ee5352e60f5c)

**Closed as completed** 2024-11-11 20:35 UTC
Labels: type_bug, dashboard
