### ISSUE TITLE
🐞 (Qanet)[Bug]: the error color of grace period dedicated node is weird 

### ISSUE THREAD

**Issue by khaledyoussef24** [threefoldtech/tfgrid-sdk-ts#2572] opened 2024-04-16 14:58 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### which package/s did you face the problem with?

Dashboard

### What happened?

rented a dedicated node and let it go to grace period and then tried to deploy the error message were clear but the color was weird.

https://github.com/threefoldtech/tfgrid-sdk-ts/issues/1390

### which network/s did you face the problem on?

Dev

### version

a03d4ed

### Relevant screenshots/screen records

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/c73918a0-58eb-4958-ac7e-dcecba52ece7)

### Relevant log output

```console
na
```

**Comment by samaradel** [comment] 2024-05-07 11:36
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/11662805/a5bdef98-537f-4154-a32c-70f5d255c917)
validation on the input now I can't reproduce the issue

**Comment by khaledyoussef24** [comment] 2024-05-19 02:44
The error is still producible.
steps to produce:

1. rent a node.
2. transfer all the tfts to another account.
3. wait for the billing cycle.
4. try to deploy on dedicated node.

, is the color of the error acceptable or should it be red?


![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/646755d2-5422-4add-925b-4977e8c238a8)

**Comment by samaradel** [comment] 2024-05-19 09:24
### Work Completed: 
Fix nodes contract in grace period toast

**Comment by A-Harby** [comment] 2024-06-12 14:02
The toast is fixed in the manual selection, But the deploy button is enabled and when I deploy, it gives me an error, which the wrong error message also.

The load node should give me an error on both automatic and manual selection because the rented node is on a grace period.

[screen-capture (34).webm](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/6fea6bd4-cfb5-456e-80ba-cbbe78640d57)

**Comment by samaradel** [comment] 2024-06-13 12:27
It's a different issue now. please create an issue for the behavior

**Comment by A-Harby** [comment] 2024-06-25 10:11
Verified, QA 2.5.0-rc3.

The color and alert are now clear. 
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/eae4df80-e1d0-4f57-8a7d-4d77e90f8866)

I created another issue for deploying https://github.com/threefoldtech/tfgrid-sdk-ts/issues/3025.

**Closed** 2024-06-27 14:07 UTC
Labels: type_bug, dashboard
