### ISSUE TITLE
🐞 [Bug]: Delete validation is different than deploy validation

### ISSUE THREAD

**Issue by A-Harby** [threefoldtech/tfgrid-sdk-ts#3318] opened 2024-08-19 14:29 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### which package/s did you face the problem with?

Dashboard

### What happened?

I deployed a VM with no error (passing the validation) but when I try to delete it, I get this error `deployment_name must contain only letters and numbers` and can't delete it.

### which network/s did you face the problem on?

Dev

### version

28e17de

### Relevant screenshots/screen records

![image](https://github.com/user-attachments/assets/88d81e31-d731-4a66-a5b6-4b48914c1509)
![image](https://github.com/user-attachments/assets/0f8b4c29-e51f-4107-971c-7fda7c9a48ab)

### Relevant log output

```console
Validation failed. errors: Array(1) [Object(5) {"target": Object(2) {"name": test_omar, "deployment_name": test_omar}, "value": test_omar, "property": deployment_name, "children": Array(0) [], "constraints": Object(1) {"isAlphanumeric": deployment_name must contain only letters and numbers}}]

Error while deleting deployment ValidationError: Validation failed. errors: An instance of DeleteMachineModel has failed the validation:
- property deployment_name has failed the following constraints: isAlphanumeric 
.

error while getting value of key(VM89c30eb6) GridClientError: Couldn't decrypt key: dev/162/machines/fullvm/VM89c30eb6/contracts.json.
```

**Comment by AhmedHanafy725** [comment] 2024-08-28 09:17
duplicate of #3314

**Closed as completed by AhmedHanafy725** 2024-08-28 09:17 UTC
Labels: type_bug, dashboard
