### ISSUE TITLE
NOSTR Node (mycelium, optional pub ip)

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/tfgrid-sdk-ts#2010] opened 2024-01-17 05:44 UTC

**Comment by MohamedElmdary** [comment] 2024-02-14 15:19
require nostr image

**Comment by zaelgohary** [comment] 2024-06-09 13:35
@maxux Can you promote this flist? https://hub.grid.tf/petep.3bot/nostr_relay-mycelium.flist.md

**Comment by zaelgohary** [comment] 2024-06-09 13:39
@ehab-hassan Can you provide a suitable logo for this app?

**Comment by zaelgohary** [comment] 2024-06-09 14:26
WIP:

Added Nostr to the applications list. Waiting for the logo and the list to be promoted and the PR will be ready for review.

**Comment by zaelgohary** [comment] 2024-06-10 11:52
Blocked on the logo & flist.

**Comment by maxux** [comment] 2024-06-10 12:06
Promoted: https://hub.grid.tf/tf-official-apps/nostr_relay-mycelium.flist.md

**Comment by ehab-hassan** [comment] 2024-06-12 08:37
@zaelgohary Nostr logo white
![nostr](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/10484295/56e2c189-3760-459f-bd29-51927edf77ae)

**Comment by khaledyoussef24** [comment] 2024-07-04 06:40
i deployed the application and it is working fine and can connect to the machine but is this solution domain is not generated 

![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/b74127bd-dfc4-4a15-b625-5d39a5dbb29c)
![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/6ea3b4d5-81fd-4915-b854-8b12194d4cb9)
![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/a40e9713-4965-46d5-9b9c-ee590e2734fa)
![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/ed76ab84-953e-41a9-b56b-b71a2c93d45c)

**Comment by Mik-TF** [comment] 2024-07-04 15:58
I agree with @khaledyoussef24 here: I think we could add the possibility for the domain + Visit button to access the Nostr instance. It would be on par with the other solutions we present on the Dashboard. Also, wireguard network isn't there.

**Feature Requests**

- Add a possibility to set a domain + gateway
- Add a Visit button leading to the Nostr instance
- Add the WireGuard option

Can we have these updates now or would they come at a later release?
Either way is fine, I ask to coordinate with the info_grid docs.

**Comment by zaelgohary** [comment] 2024-07-23 06:32
@Mik-TF Is Nostr doc ready on the manual? I searched for it but couldn't find it.

**Comment by mik-tf** [comment] 2024-07-23 12:56
It's in a draft PR as some work still needs to be done on the dev side: https://github.com/threefoldtech/info_grid/pull/592 (see my reply just above)

**Comment by zaelgohary** [comment] 2024-07-24 07:52
WIP:

Added the requested changes, however, I'm facing an error related to the network while deploying. Still looking into it.

**Comment by zaelgohary** [comment] 2024-07-24 08:58
Work completed:

The previous error was caused by disabling the access while adding the gateway. Fixed by adding access & setting the access node.

**Comment by khaledyoussef24** [comment] 2024-07-30 06:53
verified on stagging
network :devnet
version : ac03039


![Image](https://github.com/user-attachments/assets/8a0ee01f-90db-491f-ad76-e0c247626377)
![Image](https://github.com/user-attachments/assets/7c55c4a7-7556-43d1-b1a5-d4151c092d58)
![Image](https://github.com/user-attachments/assets/fbb6327d-42ec-4927-94de-c500cdf0b07d)



![Image](https://github.com/user-attachments/assets/0ea1b507-44cb-40a6-9032-95848d28d580)



![Image](https://github.com/user-attachments/assets/3413dc70-c26c-4cd9-9535-d0f828a6d962)

[test case 1
](https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=422332#case_4325474)
[test case 2](https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=422332#case_4325475)

**Comment by mik-tf** [comment] 2024-07-31 18:20
Work done on info_grid's side.

**Comment by zaelgohary** [comment] 2024-08-01 11:07
> Work done on info_grid's side.

Nostr docs giving 404.

![image](https://github.com/user-attachments/assets/14259878-be03-4422-81d8-866609cc252f)

**Comment by mik-tf** [comment] 2024-08-01 12:00
It's not yet merged. ongoing pr: https://github.com/threefoldtech/info_grid/pull/592

**Closed** 2024-08-07 08:33 UTC
Labels: dashboard
