### ISSUE TITLE
🐞 [Bug]: `lazy load` Error while listing contracts due: Error while loading contracts: ValidationError: url should be provided

### ISSUE THREAD

**Issue by Mahmoud-Emad** [threefoldtech/tfgrid-sdk-ts#3359] opened 2024-09-03 11:41 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### which package/s did you face the problem with?

Dashboard

### What happened?

it happens when opening the contracts page before connecting the wallet, after connecting it you'll see the error.

### Steps To Reproduce

1. Go to the dashboard
2. Go to the contracts page
3. Connect the wallet
4. open a new window with the same URL of contracts list page
5. connect another wallet

### which network/s did you face the problem on?

Dev

### version

Development

### Relevant screenshots/screen records

![image](https://github.com/user-attachments/assets/b0fc02f4-a3c7-47bc-8930-564f74a13b89)
![image](https://github.com/user-attachments/assets/9eb1a5b6-c0e3-4a9d-88f6-4d943ed0e241)

### Relevant log output

```console
N/A
```

**Comment by amiraabouhadid** [comment] 2024-09-05 11:02
might also be caused by lazy loading :( similar to #3322

**Comment by 0oM4R** [comment] 2024-09-30 12:56
should be fixed in https://github.com/threefoldtech/tfgrid-sdk-ts/pull/3475

**Comment by khaledyoussef24** [comment] 2024-10-18 07:20
issue is no longer reproducable on devnet
version fccc6af
![Image](https://github.com/user-attachments/assets/a4ba2eed-414d-4108-9e48-3928fda19087)

**Closed as completed** 2024-10-23 19:05 UTC
Labels: type_bug
