### ISSUE TITLE
Unable to connect to Grid3 HTTP server due to "Maximum number of attempts exceeded" error

### ISSUE THREAD

**Issue by Tanguille** [threefoldtech/tfgrid-sdk-ts#194] opened 2023-04-27 10:19 UTC
## Description

When running the Grid3 HTTP server using the command yarn grid_http_server -c config.json, I am unable to connect to the server and receive the following error message:

"Error: Unable to connect due to Maximum number of attempts exceeded."

I have checked my configuration file and it seems to be correct.

### Steps to Reproduce

1. Install the package via `yarn add @threefold/grid_http_server`

2. Run the command yarn grid_http_server -c config.json.

### Expected Behavior

The server keeps running without Error.

### Actual Behavior

After a few seconds I see :
`Error: Unable to connect due to Maximum number of attempts exceeded at GridClient.connect (/home/tanguille/Documents/Software/ProgrammerenHoGent/Stage/naiein/rust_backend/grid3_client_ts/src/client.ts:107:23)
at async HttpServer.register (/home/tanguille/Documents/Software/ProgrammerenHoGent/Stage/naiein/rust_backend/grid3_client_ts/src/server/http_server.ts:71:9)`

## Context

This used to run on 25 april without issues albeit on the now archived version of grid3_client_ts, which now also doesn't work anymore.

**Comment by AhmedHanafy725** [comment] 2023-04-27 11:59
just tried the same steps provided and it worked fine.

maybe it's a network issue. can you try it again? and also provide the network used (dev, test, or main)?

**Comment by Tanguille** [comment] 2023-04-27 12:46
Now it works with the new version so it was probably temporary. I am using the dev net.

**Comment by Tanguille** [comment] 2023-05-02 14:20
I have been having this issue for the entire day again on the dev network with `"@threefold/grid_http_server": "^2.0.0-rc4",
    "ts-node": "^10.9.1"` as dependencies

**Comment by Mahmoud-Emad** [comment] 2023-05-09 07:55
Hi @Tanguille, 
I have tested this many times and it seems to be working correctly without any issues on my end. However, it is possible that the issue may lie with your network.

**Comment by Tanguille** [comment] 2023-05-09 08:24
Thanks for testing @Mahmoud-Emad. For me it seems to work most of the time, it is really only occasionally that I have this issues, could that be just maintenance on the dev network or something?

**Comment by xmonader** [comment] 2023-05-22 11:41
@Tanguille i have to close the issue, for us we can't reproduce, but please if you found a more reproducible way, reopen

**Closed by xmonader** 2023-05-22 11:41 UTC
