### ISSUE TITLE
Can't enter Dashboard from a new account

### ISSUE THREAD

**Issue by zaelgohary** [threefoldtech/tfgrid-sdk-ts#779] opened 2023-07-09 13:19 UTC
It rejects every time I try to accept the terms & conditions

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/40770501/895fb68e-936f-4fb5-9932-8a8fa88ce283)

logs:

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/40770501/4f6dec0a-8e55-4d5f-99b2-a2cc5d57aead)

**Comment by Omarabdul3ziz** [comment] 2023-07-13 08:53
can't reproduce the issue, i tried the mentioned scenario multiple times and it works fine

**Comment by mohamedamer453** [comment] 2023-07-13 10:38
I tried to reproduce this issue with 10+ new accounts but unfortunately i wasn't able to, however the same console error that appeared always appears along with other errors so i created a separate issue for it. #806 

So i'll close this one for now but please reopen it if it was reproducible.

**Closed by mohamedamer453** 2023-07-13 10:38 UTC
Labels: type_bug, dashboard
